import {createHash} from 'node:crypto';
import {GmailService,GmailError,gmailAccount,type GmailOptions} from '../gmail';
import {GOOGLE_WORKSPACE_SCOPE,type GoogleSelection,type GoogleWorkspaceState,type GoogleImportReceipt,type GoogleWorkspaceCommand} from '../contracts/google-workspace';
export type {GoogleSelection,GoogleWorkspaceState,GoogleImportReceipt};
const MAX_BYTES=1024*1024;
const errors:Record<string,string>={account_mismatch:'Connect, verify and approve the exact Google account for this project before importing.',busy:'A Google operation is already in progress. Try again when it finishes.',invalid_selection:'Choose one Google Drive file or a bounded sheet range such as Sheet1!A1:H100.',unsupported_file:'This import supports text, CSV, JSON, Markdown, PDF, and Google Docs. Choose a bounded range for a Google Sheet.',too_large:'The selected input exceeds the 1 MiB, 1,000-row, or 32-column import limit. Choose a smaller input.',source_changed:'This source changed during import. Nothing was imported; try again.',response_invalid:'Google returned an invalid or oversized file response.',not_downloadable:'This selected file cannot be downloaded, is deleted, or is a shortcut. Select an accessible original file.',invalid_command:'The Google import command is invalid.'};
export class GoogleWorkspaceError extends Error {constructor(readonly code:string,message?:string){super(message||errors[code]||'The selected Google input could not be imported.');this.name='GoogleWorkspaceError';}}
function fail(code:string):never{throw new GoogleWorkspaceError(code);}
function record(v:unknown):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||![Object.prototype,null].includes(Object.getPrototypeOf(v)))fail('response_invalid');return v as Record<string,unknown>;}
function convert(error:unknown):never{if(error instanceof GoogleWorkspaceError)throw error;if(error instanceof GmailError)throw new GoogleWorkspaceError(error.code,error.message.replaceAll('Gmail','Google Drive').replace('No message contents were read','No file contents were read').replace('Existing unread status was preserved.','No source files were changed.'));throw new GoogleWorkspaceError('response_invalid');}
export function googleResourceId(raw:unknown):string{
 if(typeof raw!=='string'||raw.length>2048)fail('invalid_selection');const text=raw.trim();if(/^[A-Za-z0-9_-]{5,200}$/.test(text))return text;
 try{const url=new URL(text);if(url.protocol!=='https:'||url.username||url.password||url.port)fail('invalid_selection');let id:string|undefined;if(url.hostname==='docs.google.com')id=url.pathname.match(/^\/(?:document|spreadsheets)\/d\/([A-Za-z0-9_-]{5,200})(?:\/|$)/)?.[1];if(url.hostname==='drive.google.com')id=url.pathname.match(/^\/file\/d\/([A-Za-z0-9_-]{5,200})(?:\/|$)/)?.[1]||(url.pathname==='/open'&&url.searchParams.getAll('id').length===1?url.searchParams.get('id')||undefined:undefined);if(!id||!/^[A-Za-z0-9_-]{5,200}$/.test(id))fail('invalid_selection');return id;}catch{return fail('invalid_selection');}
}
export function boundedSheetRange(raw:unknown):{range:string;rows:number;columns:number}{
 if(typeof raw!=='string'||raw.length>256||/[\x00-\x1f\x7f]/.test(raw))fail('invalid_selection');const range=raw.trim(),m=range.match(/^((?:'(?:[^']|'')+'|[A-Za-z0-9_ -]+)!)\$?([A-Z]{1,3})\$?([1-9][0-9]{0,6}):\$?([A-Z]{1,3})\$?([1-9][0-9]{0,6})$/);if(!m)fail('invalid_selection');const column=(s:string)=>[...s].reduce((n,c)=>n*26+c.charCodeAt(0)-64,0),rows=Number(m[5])-Number(m[3])+1,columns=column(m[4])-column(m[2])+1;if(rows<1||columns<1)fail('invalid_selection');if(rows>1000||columns>32||rows*columns>20000)fail('too_large');return{range,rows,columns};
}
export function parseGoogleSelection(raw:unknown):GoogleSelection{const v=record(raw);if(v.kind==='drive_file'&&Object.keys(v).length===2&&Object.hasOwn(v,'resourceId'))return{kind:v.kind,resourceId:googleResourceId(v.resourceId)};if(v.kind==='sheet_range'&&Object.keys(v).length===3&&Object.hasOwn(v,'resourceId'))return{kind:v.kind,resourceId:googleResourceId(v.resourceId),range:boundedSheetRange(v.range).range};return fail('invalid_selection');}
export function parseGoogleWorkspaceCommand(raw:unknown):GoogleWorkspaceCommand{const v=record(raw),id=(x:unknown)=>{if(typeof x!=='string'||!/^[-A-Za-z0-9_]{1,128}$/.test(x))fail('invalid_command');return x;};if(v.type==='googleWorkspace.state'||v.type==='googleWorkspace.disconnect'||v.type==='googleWorkspace.verify'){if(Object.keys(v).length!==1)fail('invalid_command');return{type:v.type};}if(v.type==='googleWorkspace.connect'&&Object.keys(v).length===3)return{type:v.type,projectId:id(v.projectId),account:gmailAccount(v.account)};if(v.type==='googleWorkspace.import'&&Object.keys(v).every(k=>['type','projectId','agentId','taskId','selection'].includes(k)))return{type:v.type,projectId:id(v.projectId),agentId:id(v.agentId),...(v.taskId!==undefined?{taskId:id(v.taskId)}:{}),selection:parseGoogleSelection(v.selection)};return fail('invalid_command');}
interface Metadata {id:string;name:string;mime:string;version:string;modifiedTime:string;size:number|null}
function metadata(v:Record<string,unknown>,id:string):Metadata{if(v.id!==id||typeof v.name!=='string'||!v.name||v.name.length>1000||typeof v.mimeType!=='string'||typeof v.version!=='string'||!/^\d{1,30}$/.test(v.version)||typeof v.modifiedTime!=='string'||!Number.isFinite(Date.parse(v.modifiedTime)))fail('response_invalid');if(v.trashed!==false||record(v.capabilities).canDownload!==true||v.mimeType==='application/vnd.google-apps.shortcut'||v.mimeType==='application/vnd.google-apps.folder')fail('not_downloadable');const size=v.size===undefined?null:Number(v.size);if(size!==null&&(!Number.isSafeInteger(size)||size<0))fail('response_invalid');if(size!==null&&size>MAX_BYTES)fail('too_large');return{id,name:v.name.replace(/[\x00-\x1f\x7f]/g,'').slice(0,256),mime:v.mimeType,version:v.version,modifiedTime:v.modifiedTime,size};}
const TYPES:Record<string,{ext:string;mime:string}>={'text/plain':{ext:'txt',mime:'text/plain'},'text/csv':{ext:'csv',mime:'text/csv'},'text/tab-separated-values':{ext:'tsv',mime:'text/tab-separated-values'},'text/markdown':{ext:'md',mime:'text/markdown'},'application/json':{ext:'json',mime:'application/json'},'application/pdf':{ext:'pdf',mime:'application/pdf'}};
function filename(name:string,extension:string){return(name.replace(/\.[a-z0-9]{1,8}$/i,'').replace(/[/\\\x00-\x1f\x7f:]/g,'_').trim().slice(0,100)||'selected-input')+'.'+extension;}
function checkBytes(bytes:Buffer,mime:string){if(!bytes.length||bytes.length>MAX_BYTES)fail('too_large');if(mime==='application/pdf'){if(!bytes.subarray(0,5).equals(Buffer.from('%PDF-')))fail('response_invalid');return;}try{const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(text.includes('\0'))fail('response_invalid');if(mime==='application/json')JSON.parse(text);}catch{fail('response_invalid');}}
export interface SelectedGoogleInput {filename:string;mime:string;bytes:Buffer;source:GoogleImportReceipt}
/** Owner-selected read-only imports. No listing, sharing, source edits, or background synchronization. */
export class GoogleWorkspaceService {
 private connection:GmailService;
 constructor(options:Omit<GmailOptions,'resource'>){this.connection=new GmailService({...options,resource:'drive'});}
 private async state(work:()=>Promise<{configured:boolean;connectedAccount:string|null;connecting:boolean;error:string|null}>):Promise<GoogleWorkspaceState>{try{const state=await work();return{...state,error:state.error?.replaceAll('Gmail','Google Drive')||null,scope:GOOGLE_WORKSPACE_SCOPE,access:'selected_imports',setupMode:'owner_desktop_client',liveAccessTested:!!state.connectedAccount&&this.connection.verifiedConnectedAccount()===state.connectedAccount};}catch(error){return convert(error);}}
 status(){return this.state(()=>this.connection.status());}
 importClient(json:string){return this.state(()=>this.connection.importClient(json));}
 connect(account:string){return this.state(()=>this.connection.connect(account));}
 disconnect(){return this.state(()=>this.connection.disconnect());}
 async verifyConnection(account:string){try{await this.connection.verifyConnection(account);return this.status();}catch(error){return convert(error);}}
 verifiedConnectedAccount(){return this.connection.verifiedConnectedAccount();}
 close(){return this.connection.close();}
 async importSelected(account:string,raw:GoogleSelection,{signal}:{signal?:AbortSignal}={}):Promise<SelectedGoogleInput>{const selection=parseGoogleSelection(raw);try{return await this.connection.readSelectedSession(account,async session=>{
  const root=`https://www.googleapis.com/drive/v3/files/${selection.resourceId}`,metaURL=root+'?supportsAllDrives=true&fields=id,name,mimeType,size,version,modifiedTime,trashed,capabilities(canDownload)',before=metadata(await session.json(metaURL,32768),selection.resourceId);let bytes:Buffer,mime:string,name:string,rowCount:number|undefined,columnCount:number|undefined;const warnings:string[]=[];
  if(selection.kind==='sheet_range'){
   if(before.mime!=='application/vnd.google-apps.spreadsheet')fail('unsupported_file');const bounds=boundedSheetRange(selection.range),url=new URL(`https://sheets.googleapis.com/v4/spreadsheets/${selection.resourceId}/values/${encodeURIComponent(bounds.range)}`);url.searchParams.set('majorDimension','ROWS');url.searchParams.set('valueRenderOption','UNFORMATTED_VALUE');url.searchParams.set('dateTimeRenderOption','SERIAL_NUMBER');const data=await session.json(url.href,MAX_BYTES);if(data.majorDimension!=='ROWS'||typeof data.range!=='string'||data.values!==undefined&&!Array.isArray(data.values))fail('response_invalid');const rows=(data.values||[]) as unknown[];if(rows.length>bounds.rows)fail('response_invalid');let escaped=0;const csv=rows.map(row=>{if(!Array.isArray(row)||row.length>bounds.columns)fail('response_invalid');return Array.from({length:bounds.columns},(_,i)=>{const cell=row[i]??'';if(!['string','number','boolean'].includes(typeof cell)||typeof cell==='number'&&!Number.isFinite(cell))fail('response_invalid');let value=String(cell);if(value.includes('\0')||Buffer.byteLength(value)>65536)fail('response_invalid');if(typeof cell==='string'&&/^\s*[=+\-@]/.test(value)){value="'"+value;escaped++;}return '"'+value.replaceAll('"','""')+'"';}).join(',');}).join('\r\n');bytes=Buffer.from(csv+'\r\n');mime='text/csv';name=filename(before.name,'csv');rowCount=rows.length;columnCount=bounds.columns;if(!rows.length)fail('response_invalid');warnings.push('Only the selected range was imported. Values are computed values; date cells may use Google serial numbers.');if(escaped)warnings.push(`${escaped} text cells were prefixed with an apostrophe to prevent spreadsheet formula execution on export.`);
  }else{
   const googleDoc=before.mime==='application/vnd.google-apps.document',type=googleDoc?TYPES['text/plain']:TYPES[before.mime];if(!type)fail('unsupported_file');mime=type.mime;name=filename(before.name,type.ext);const url=googleDoc?root+'/export?mimeType=text%2Fplain':root+'?alt=media&supportsAllDrives=true';bytes=await session.bytes(url,MAX_BYTES);if(googleDoc)warnings.push('Google Docs formatting, comments, images, and embedded content are not included in the plain-text snapshot.');
  }
  try{checkBytes(bytes,mime);const after=metadata(await session.json(metaURL,32768),selection.resourceId);if(before.version!==after.version||before.modifiedTime!==after.modifiedTime||before.mime!==after.mime)fail('source_changed');const source:GoogleImportReceipt={source:selection.kind==='sheet_range'?'google_sheets':'google_drive',account:account.toLowerCase(),accountVerified:true,resourceId:selection.resourceId,resourceName:before.name,resourceVersion:before.version,modifiedTime:before.modifiedTime,...(selection.kind==='sheet_range'?{range:selection.range,rowCount,columnCount}:{}),retrievedAt:session.now(),sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,readOnly:true,scope:'explicit_selection',providerScope:GOOGLE_WORKSPACE_SCOPE,warnings};return{filename:name,mime,bytes,source};}catch(error){bytes.fill(0);throw error;}
 },{signal});}catch(error){return convert(error);}}
}
