// Production React panels; synthetic exact records only, no application main or credentials.
import React from 'react';import {createRoot} from 'react-dom/client';
import {ResultsPanel} from '../../apps/desktop/renderer/Results';import {ExactGrants} from '../../apps/desktop/renderer/Grants';import {CodePanel} from '../../apps/desktop/renderer/Code';import {FilesProvider} from '../../apps/desktop/renderer/Files';import '../../apps/desktop/renderer/styles.css';
const w=window as any,root=createRoot(document.getElementById('root')!),off=()=>()=>{};
const task=(id:string):any=>({id,agentId:'agent',state:'succeeded',executionMode:'live',objective:id,completionCriteria:'Exact synthetic task',revision:1,generation:1});
const version=(id:string):any=>({id,artifactId:'artifact-'+id,displayName:id,version:1,format:'text',mimeType:'text/plain',bytes:30,sha256:'a'.repeat(64),status:'ready',createdAt:1,visibility:'private'});
const result=(id:string):any=>({taskId:id,agentId:'agent',objective:id,completionCriteria:'Exact criteria '+id,version:version('final-'+id),costUsd:0,limits:{maxCostUsd:1,maxModelCalls:10,maxToolSteps:20,maxTokens:10000,maxActiveSeconds:60},model:'synthetic',review:{state:'accepted',revision:1,feedback:'',updatedAt:1},revisionOf:null});
const detail=(id:string):any=>({result:result(id),preview:{version:version('final-'+id),text:'Saved final '+id,truncated:false,note:null},inputs:[version('source-exact')],supportingOutputs:[version('support-exact')],evidence:[{id:'receipt-exact',tool:'read_file',label:'Exact technical receipt',createdAt:1}],totalEvidence:1,evidenceTruncated:false,integrity:'verified',quality:null,provenance:{inputRoles:[{slotKey:'source-role',versionId:'source-exact'}],routine:null,assessment:{sourceVersionId:'final-'+id,sourceSha256:'a'.repeat(64)},acceptance:{state:'accepted',revision:1}}});
const execution=(id:string,taskId:string,older=false):any=>({id,taskId,runtime:'python',origin:'owner',command:'python3 -I script.py',cwd:'/workspace',timeoutSeconds:30,cleanupState:'resolved',lifecycle:'succeeded',startedAt:older?1:2,finishedAt:3,durationMs:1,exitCode:0,source:'print("synthetic")',stdout:'Log '+id,stderr:'',logsTruncated:false,outputVersionIds:[],inputs:[],workspaceCommitted:true,workspaceRevision:1,imageDigest:'synthetic',limits:{}});
const codeState=(id:string,history=false):any=>({taskId:id,runtime:{ready:true,packages:[],imageDigest:'synthetic',message:null},executions:[execution((history?'older-':'latest-')+id,id,history)],activeExecutionId:null,dependencies:[],inputs:[],workspace:{revision:1,bytes:0},effectiveLimits:{resources:{memoryMiB:512,workspaceMiB:32,tmpMiB:8,pids:64,timeoutSeconds:30,exportBytes:1048576},sourceBytes:65536,storageBudgetBytes:100000},workspaceChanges:{revision:1,parentRevision:0,added:['outputs/exact.txt'],removed:[],modified:[]},history:{hasMore:!history}});
const grant=(id:string,current=true):any=>({requestId:'grant-'+id+(current?'':'-historical'),taskId:id,capability:{name:'upload',origin:'https://synthetic.invalid',versionIds:['version-'+id]},currentAuthority:current,authorityReason:current?'Authorized exact future use':'Previous authority ended',grantedAt:1});
let mode='results',selected='old-exact',calls:any[]=[],holdType='',failType='',pending:any[]=[];let revoked=false;
const snapshot:any={agents:[{id:'agent',name:'Synthetic agent'}],tasks:[task('old-exact'),task('task-a'),task('task-b')],artifacts:[version('support-exact')],taskArtifacts:[],workspaceSnapshots:[],storage:{usedBytes:0,budgetBytes:100000},settings:{theme:'light'},messages:[],requests:[],events:[]};
function respond(c:any){if(c.type==='results.state')return {results:[result('newest')],revisionJobs:[]};if(c.type==='results.inspect')return {results:[result('newest')],revisionJobs:[],detail:detail(c.taskId)};if(c.type==='grants.list')return [{...grant(c.taskId,!revoked),requestId:'grant-'+c.taskId},grant(c.taskId,false)];if(c.type==='grants.revoke'){revoked=true;return [];}if(c.type==='code.history')return codeState(c.taskId,true);if(c.type==='code.state')return codeState(c.taskId);if(c.type==='preview')return {version:version(c.id),text:'Supporting exact bytes',truncated:false,note:null};return {snapshot};}
async function invoke(c:any){calls.push(c);if(failType===c.type){failType='';throw Error('Synthetic '+c.type+' failure');}if(holdType===c.type)return new Promise((resolve,reject)=>pending.push({c,resolve,reject}));return respond(c);}
const bridge:any={projects:async()=>({projects:[],agents:[],memberships:[],gmailAccounts:[]}),onGmailChanged:off,onGoogleWorkspaceChanged:off,onChanged:off,onFilesChanged:off,onCodeChanged:off,results:invoke,grants:invoke,code:invoke,preview:(id:string)=>invoke({type:'preview',id}),command:invoke,files:invoke};
function render(){root.render(<FilesProvider bridge={bridge} snapshot={snapshot}>{mode==='results'?<ResultsPanel bridge={bridge} snapshot={snapshot} selectedTaskId={selected}/>:mode==='grants'?<ExactGrants bridge={bridge} taskId={selected}/>:<CodePanel bridge={bridge} snapshot={snapshot} task={task(selected)} onFiles={()=>{}}/>}</FilesProvider>);}
w.fixture={show(next:string,id:string){mode=next;selected=id;calls=[];holdType='';failType='';pending=[];revoked=false;render();},switch(id:string){selected=id;render();},hold(type:string){holdType=type;},fail(type:string){failType=type;},release(index=0){const p=pending.splice(index,1)[0];if(!p)throw Error('No pending read');p.resolve(respond(p.c));},reject(){const p=pending.shift();p.reject(Error('Synthetic '+p.c.type+' failure'));},clearHold(){holdType='';},pending:()=>pending.map(p=>p.c),calls:()=>structuredClone(calls)};
