import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,realpath,mkdir,writeFile,lstat,symlink,rm,appendFile,chmod} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {scanScript} from '../../packages/repository-snapshot/scan';
import {deflateSync} from 'node:zlib';import {createHash} from 'node:crypto';
const execute=promisify(execFile);
test('independent C07 scanner rejects replaced selected identity and cannot follow nested directory symlinks',async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),'repository-independent-')));try{const selected=join(root,'selected'),other=join(root,'outside');await mkdir(selected);await mkdir(other);await writeFile(join(other,'confidential.txt'),'outside sentinel never captured');await writeFile(join(selected,'safe.txt'),'reviewed code');await symlink(other,join(selected,'nested'));const expected=await lstat(selected);await assert.rejects(execute('/usr/bin/python3',['-c',scanScript,other,String(expected.dev),String(expected.ino)],{maxBuffer:131072,timeout:10000}),/selected folder changed/);const output=await execute('/usr/bin/python3',['-c',scanScript,selected,String(expected.dev),String(expected.ino)],{maxBuffer:131072,timeout:10000});const scan=JSON.parse(output.stdout);assert.equal(scan.entries.length,1);assert.equal(scan.entries[0].text,'reviewed code');assert(scan.exclusions.some((e:any)=>e.path==='nested'&&e.reason==='symbolic link'));assert(!output.stdout.includes('outside sentinel'));}finally{await rm(root,{recursive:true,force:true});}});
test('independent C07 scanner discloses traversal truncation with finite serialized evidence',async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),'repository-bounded-')));try{for(let n=0;n<300;n++)await writeFile(join(root,'source-'+String(n).padStart(3,'0')+'.txt'),'bounded code '+n);const expected=await lstat(root);const output=await execute('/usr/bin/python3',['-c',scanScript,root,String(expected.dev),String(expected.ino)],{maxBuffer:131072,timeout:10000});const scan=JSON.parse(output.stdout);assert(scan.entries.length<=16);assert(scan.entries.reduce((n:number,e:any)=>n+e.bytes,0)<=32768);assert(scan.exclusions.some((e:any)=>e.reason.includes('scan limit')));assert(Buffer.byteLength(output.stdout)<=65536);}finally{await rm(root,{recursive:true,force:true});}});

test('independent C07 rejects trailing compressed-object data and never executes local Git configuration',async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),'repository-git-review-')));try{const git=(...args:string[])=>execute('git',['-C',root,...args]);await git('init');await git('config','user.name','Synthetic reviewer');await git('config','user.email','synthetic@example.invalid');await writeFile(join(root,'source.txt'),'source bytes');await git('add','.');await git('commit','-m','synthetic');const head=(await git('rev-parse','HEAD')).stdout.trim();const marker=join(root,'never-run');await git('config','core.fsmonitor','touch '+marker);await git('config','core.hooksPath',join(root,'unsafe-hooks'));const expected=await lstat(root);const scan=async()=>JSON.parse((await execute('/usr/bin/python3',['-c',scanScript,root,String(expected.dev),String(expected.ino)],{maxBuffer:131072,timeout:10000})).stdout);assert.equal((await scan()).metadata.commit,head);await assert.rejects(lstat(marker),{code:'ENOENT'});const objectPath=join(root,'.git','objects',head.slice(0,2),head.slice(2));await chmod(objectPath,0o600);await appendFile(objectPath,Buffer.from('trailing untrusted bytes'));assert.equal((await scan()).metadata,null);await assert.rejects(lstat(marker),{code:'ENOENT'});}finally{await rm(root,{recursive:true,force:true});}});

test('independent C07 loose-object decompression bomb remains unknown with captured source intact',async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),'repository-bomb-review-')));try{await mkdir(join(root,'.git','objects'),{recursive:true});const content=Buffer.from('x'.repeat(2*1024*1024)),raw=Buffer.concat([Buffer.from('commit '+content.length+'\0'),content]),id=createHash('sha1').update(raw).digest('hex');await mkdir(join(root,'.git','objects',id.slice(0,2)));await writeFile(join(root,'.git','HEAD'),id+'\n');await writeFile(join(root,'.git','objects',id.slice(0,2),id.slice(2)),deflateSync(raw));await writeFile(join(root,'source.txt'),'safe source remains');const expected=await lstat(root),output=await execute('/usr/bin/python3',['-c',scanScript,root,String(expected.dev),String(expected.ino)],{maxBuffer:131072,timeout:10000}),scan=JSON.parse(output.stdout);assert.equal(scan.metadata,null);assert.equal(scan.entries[0].text,'safe source remains');assert(Buffer.byteLength(output.stdout)<65536);}finally{await rm(root,{recursive:true,force:true});}});

test('independent C07 FIFO replacement between stat and open cannot block or become source evidence',async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),'repository-fifo-review-')));try{await writeFile(join(root,'victim.txt'),'ordinary file before swap');await writeFile(join(root,'safe.txt'),'safe surviving source');const expected=await lstat(root);const instrument=String.raw`
import os
_original_open=os.open
_swapped=False
def _swap_leaf(path,flags,*args,**kwargs):
 global _swapped
 if path=='victim.txt' and not _swapped and kwargs.get('dir_fd') is not None:
  _swapped=True
  os.unlink(path,dir_fd=kwargs['dir_fd'])
  os.mkfifo(os.path.join(sys.argv[1],path),0o600)
 return _original_open(path,flags,*args,**kwargs)
os.open=_swap_leaf
`;
 const output=await execute('/usr/bin/python3',['-c',instrument+'\n'+scanScript+'\nassert _swapped, "swap never exercised"',root,String(expected.dev),String(expected.ino)],{maxBuffer:131072,timeout:1500});const scan=JSON.parse(output.stdout);assert.equal(scan.entries.length,1);assert.equal(scan.entries[0].text,'safe surviving source');assert(scan.exclusions.some((e:any)=>e.path==='victim.txt'&&e.reason==='changed or unsafe file'));assert.equal((await lstat(join(root,'victim.txt'))).isFIFO(),true);}finally{await rm(root,{recursive:true,force:true});}});

test('independent C07 external hardlink is excluded without capturing the outside sentinel',async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),'repository-hardlink-review-')));try{const selected=join(root,'selected');await mkdir(selected);const outside=join(root,'outside.txt');await writeFile(outside,'outside hardlink sentinel never captured');const {link}=await import('node:fs/promises');await link(outside,join(selected,'looks-local.txt'));await writeFile(join(selected,'safe.txt'),'only selected safe source');const expected=await lstat(selected),output=await execute('/usr/bin/python3',['-c',scanScript,selected,String(expected.dev),String(expected.ino)],{maxBuffer:131072,timeout:10000}),scan=JSON.parse(output.stdout);assert.equal(scan.entries.length,1);assert.equal(scan.entries[0].text,'only selected safe source');assert(scan.exclusions.some((e:any)=>e.path==='looks-local.txt'&&e.reason==='hard-linked file'));assert(!output.stdout.includes('outside hardlink sentinel'));}finally{await rm(root,{recursive:true,force:true});}});
