import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Coordinator} from '../../packages/coordinator';

test('scoped paginated archive keeps exact history and frees occupancy while preserving exact history',async()=>{
 const root=mkdtempSync(join(tmpdir(),'history-boundary-')),c=new Coordinator({dataRoot:root});try{await c.live.ready;c.handle({type:'settings.update',settings:{driverEnabled:false}});const a=c.handle({type:'agents.create',name:'History',instructions:''}).agents[0];for(let n=0;n<26;n++)c.handle({type:'tasks.create',agentId:a.id,objective:'Task '+n,completionCriteria:'Done',scenario:'complete'});
 const first=c.taskHistory({type:'tasks.history',scope:'active',agentId:a.id,cursor:null});assert.equal(first.tasks.length,25);assert.ok(first.nextCursor);const second=c.taskHistory({type:'tasks.history',scope:'active',agentId:a.id,cursor:first.nextCursor});assert.equal(second.tasks.length,1);assert.equal(new Set([...first.tasks,...second.tasks].map(task=>task.id)).size,26);
 const id=first.tasks[0].id;assert.throws(()=>c.taskHistory({type:'tasks.archive',taskId:id,archived:true}),/finished tasks/);c.handle({type:'tasks.cancel',taskId:id});const watermark=c.eventWatermark();const archived=c.taskHistory({type:'tasks.archive',taskId:id,archived:true});assert.equal(archived.archiveFreesCapacity,true);assert.ok(c.eventWatermark()>watermark);assert.equal(c.snapshot().tasks.length,25);const archive=c.taskHistory({type:'tasks.history',scope:'archived',agentId:a.id,cursor:null});assert.equal(archive.tasks[0].id,id);const exact=c.taskHistory({type:'tasks.inspect',taskId:id,cursor:null});assert.equal(exact.tasks[0].id,id);assert.ok(exact.messages!.some(message=>message.role==='owner'));c.taskHistory({type:'tasks.archive',taskId:id,archived:false});assert.equal(c.taskHistory({type:'tasks.history',scope:'archived',agentId:a.id,cursor:null}).tasks.length,0);assert.throws(()=>c.taskHistory({type:'tasks.inspect',taskId:id,cursor:'bad',authority:'agent'}));
 }finally{await c.shutdown();rmSync(root,{recursive:true,force:true});}
});

test('actual agent and task capacity can be reused across archived generations and restart',async()=>{
 const root=mkdtempSync(join(tmpdir(),'archive-capacity-'));let c=new Coordinator({dataRoot:root});try{await c.live.ready;c.handle({type:'settings.update',settings:{driverEnabled:false}});let agentId='';for(let n=0;n<101;n++){const before=new Set(c.snapshot().agents.map(a=>a.id));c.handle({type:'agents.create',name:'Generation '+n,instructions:''});agentId=c.snapshot().agents.find(a=>!before.has(a.id))!.id;if(n<100)c.taskHistory({type:'agents.archive',agentId,archived:true});}assert.equal(c.snapshot().agents.length,1);const agentsPage=c.taskHistory({type:'agents.history',scope:'archived',cursor:null});assert.equal(agentsPage.agents!.length,25);assert.ok(agentsPage.nextAgentCursor);let last='';for(let n=0;n<251;n++){const before=new Set(c.snapshot().tasks.map(t=>t.id));c.handle({type:'tasks.create',agentId,objective:'Generation '+n,completionCriteria:'Done',scenario:'complete'});last=c.snapshot().tasks.find(t=>!before.has(t.id))!.id;c.handle({type:'tasks.cancel',taskId:last});c.taskHistory({type:'tasks.archive',taskId:last,archived:true});}assert.equal(c.snapshot().tasks.length,0);const saved=c.taskHistory({type:'tasks.inspect',taskId:last,cursor:null});await c.shutdown();c=new Coordinator({dataRoot:root});await c.live.ready;assert.equal(c.snapshot().tasks.length,0);assert.deepEqual(c.taskHistory({type:'tasks.inspect',taskId:last,cursor:null}).messages,saved.messages);c.taskHistory({type:'tasks.archive',taskId:last,archived:false});assert.equal(c.snapshot().tasks.find(t=>t.id===last)!.state,'cancelled');assert.equal(c.snapshot().tasks.filter(t=>!t.archived).length,1);
 }finally{await c.shutdown();rmSync(root,{recursive:true,force:true});}
});
