import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {GoogleWorkspaceService,parseGoogleSelection,boundedSheetRange,googleResourceId,parseGoogleWorkspaceCommand} from '../../packages/google-workspace';
import {GOOGLE_WORKSPACE_SCOPE} from '../../packages/contracts/google-workspace';
import type {GmailSecretStore,GmailSecretKey} from '../../packages/gmail';
const account='client@example.com',id='selected_file_01';
class Store implements GmailSecretStore {values=new Map<GmailSecretKey,string>([['client',JSON.stringify({clientId:'123.apps.googleusercontent.com',clientSecret:'fixture'})],['tokens',JSON.stringify({account,accessToken:'synthetic',refreshToken:'refresh',expiresAt:Date.now()+3600000,scope:GOOGLE_WORKSPACE_SCOPE})]]);async read(k:GmailSecretKey){return this.values.get(k)||null;}async write(k:GmailSecretKey,v:string){this.values.set(k,v);}async remove(k:GmailSecretKey){this.values.delete(k);}}
const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status});
const meta=(extra:Record<string,unknown>={})=>({id,name:'Report.csv',mimeType:'text/csv',size:'16',version:'1',modifiedTime:'2026-09-30T00:00:00Z',trashed:false,capabilities:{canDownload:true},...extra});
function fixture(responder?:(url:URL,init:RequestInit,n:number)=>Response|Promise<Response>){const store=new Store(),calls:{url:URL;init:RequestInit}[]=[];const service=new GoogleWorkspaceService({store,openExternal:async()=>{throw Error('no consent in import fixture');},fetch:async(input,init={})=>{const url=new URL(String(input));calls.push({url,init});assert.equal(init.redirect,'error');assert.equal(init.method,'GET');if(url.pathname.endsWith('/about'))return json({user:{emailAddress:account}});return responder?responder(url,init,calls.length):url.searchParams.get('alt')==='media'?new Response('item,total\nx,10\n'):json(meta());}});return{store,service,calls};}

test('selection validates explicit Google IDs and finite ranges without URL endpoint authority',()=>{
 assert.equal(googleResourceId('https://docs.google.com/spreadsheets/d/selected_file_01/edit#gid=0'),id);
 assert.deepEqual(boundedSheetRange("'Report data'!A1:H100"),{range:"'Report data'!A1:H100",rows:100,columns:8});
 for(const value of ['https://evil.example/spreadsheets/d/selected_file_01','file:///etc/passwd','https://docs.google.com.evil.example/document/d/selected_file_01','https://user@docs.google.com/document/d/selected_file_01','../etc/passwd'])assert.throws(()=>googleResourceId(value));
 for(const value of ['A:Z','A1:B2','Sheet1!A1:ZZ100','Sheet1!A1:B1001','Sheet1!B2:A1','Sheet1!A0:B10'])assert.throws(()=>boundedSheetRange(value));
 assert.throws(()=>parseGoogleSelection({kind:'drive_file',resourceId:id,path:'/etc/passwd'}));assert.throws(()=>parseGoogleWorkspaceCommand({type:'googleWorkspace.import',projectId:'p',agentId:'a',selection:{kind:'drive_file',resourceId:id},account:'other@example.com'}));
 assert.deepEqual(parseGoogleWorkspaceCommand({type:'googleWorkspace.connect',projectId:'p',account:'Client@Example.com'}),{type:'googleWorkspace.connect',projectId:'p',account});
});
test('status distinguishes stored credentials from live profile verification and verifies without file reads',async()=>{const f=fixture();try{assert.equal((await f.service.status()).liveAccessTested,false);assert.equal(f.service.verifiedConnectedAccount(),null);assert.equal((await f.service.verifyConnection(account)).liveAccessTested,true);assert.equal(f.calls.length,1);assert.equal(f.calls[0].url.pathname,'/drive/v3/about');assert.equal(f.service.verifiedConnectedAccount(),account);await f.service.disconnect();assert.equal(f.service.verifiedConnectedAccount(),null);}finally{await f.service.close();}});
test('selected import checks exact account first and preserves source hash/version receipt',async()=>{const f=fixture();try{const result=await f.service.importSelected(account,{kind:'drive_file',resourceId:id});assert.equal(result.bytes.toString(),'item,total\nx,10\n');assert.equal(result.source.sha256,createHash('sha256').update(result.bytes).digest('hex'));assert.equal(result.source.resourceVersion,'1');assert.equal(result.source.accountVerified,true);assert.equal(result.source.readOnly,true);assert.equal(f.calls.length,4);assert.ok(f.calls[0].url.pathname.endsWith('/about'));assert.ok(f.calls.slice(1).every(c=>c.url.pathname.endsWith('/'+id)));assert.ok(f.calls.every(c=>c.init.method==='GET'&&!c.url.searchParams.has('access_token')));}finally{await f.service.close();}});
test('wrong cached account blocks even metadata; wrong live profile blocks file reads',async()=>{const f=fixture();try{await assert.rejects(f.service.importSelected('other@example.com',{kind:'drive_file',resourceId:id}),{code:'account_mismatch'});assert.equal(f.calls.length,0);}finally{await f.service.close();}const g=new GoogleWorkspaceService({store:new Store(),openExternal:async()=>{},fetch:async(input)=>{assert.ok(String(input).includes('/about'));return json({user:{emailAddress:'wrong@example.com'}});}});try{await assert.rejects(g.importSelected(account,{kind:'drive_file',resourceId:id}),{code:'account_mismatch'});assert.equal(g.verifiedConnectedAccount(),null);}finally{await g.close();}});
test('source changes during download reject the snapshot',async()=>{let metadataCalls=0;const f=fixture(url=>url.searchParams.get('alt')==='media'?new Response('item,total\nx,10\n'):json(meta({version:String(++metadataCalls)})));try{await assert.rejects(f.service.importSelected(account,{kind:'drive_file',resourceId:id}),{code:'source_changed'});}finally{await f.service.close();}});
test('oversized, forbidden type, shortcut, deleted or download-restricted files stop before content',async()=>{for(const extra of [{size:'1048577'},{mimeType:'application/x-executable'},{mimeType:'application/vnd.google-apps.shortcut'},{trashed:true},{capabilities:{canDownload:false}}]){const f=fixture(()=>json(meta(extra)));try{await assert.rejects(f.service.importSelected(account,{kind:'drive_file',resourceId:id}));assert.equal(f.calls.length,2);}finally{await f.service.close();}}});
test('Sheets reads selected bounded range and imports computed values with formula-safe CSV',async()=>{const f=fixture(url=>url.hostname==='sheets.googleapis.com'?json({range:'Sheet1!A1:C3',majorDimension:'ROWS',values:[['item','total','note'],['a',12,'=DANGEROUS()'],['b',-2,true]]}):json(meta({mimeType:'application/vnd.google-apps.spreadsheet',size:undefined})));try{const r=await f.service.importSelected(account,{kind:'sheet_range',resourceId:id,range:'Sheet1!A1:C3'});assert.match(r.bytes.toString(),/'=DANGEROUS/);assert.match(r.bytes.toString(),/"-2"/);assert.equal(r.source.rowCount,3);assert.equal(r.source.columnCount,3);assert.equal(r.source.range,'Sheet1!A1:C3');assert.ok(r.source.warnings.some(v=>v.includes('apostrophe')));const read=f.calls.find(c=>c.url.hostname==='sheets.googleapis.com')!;assert.equal(read.url.searchParams.get('valueRenderOption'),'UNFORMATTED_VALUE');assert.ok(decodeURIComponent(read.url.pathname).endsWith('Sheet1!A1:C3'));}finally{await f.service.close();}});
test('Sheets rejects extra returned rows/columns and nested cell values',async()=>{for(const values of [[['a','b','c']],[[{secret:'object'}]],[['a'],['b'],['c']]]){const f=fixture(url=>url.hostname==='sheets.googleapis.com'?json({range:'Sheet1!A1:B2',majorDimension:'ROWS',values}):json(meta({mimeType:'application/vnd.google-apps.spreadsheet',size:undefined})));try{await assert.rejects(f.service.importSelected(account,{kind:'sheet_range',resourceId:id,range:'Sheet1!A1:B2'}),{code:'response_invalid'});}finally{await f.service.close();}}});
test('Google Docs export is plain text and never follows a redirect',async()=>{const f=fixture(url=>url.pathname.endsWith('/export')?new Response('Project brief\n'):json(meta({name:'Brief',mimeType:'application/vnd.google-apps.document',size:undefined})));try{const r=await f.service.importSelected(account,{kind:'drive_file',resourceId:id});assert.equal(r.filename,'Brief.txt');assert.equal(r.mime,'text/plain');assert.ok(r.source.warnings.some(v=>v.includes('formatting')));assert.ok(f.calls.find(c=>c.url.pathname.endsWith('/export'))?.url.searchParams.get('mimeType')==='text/plain');}finally{await f.service.close();}});
test('bounded stream rejects deceptive length and clears selected bytes on failure',async()=>{const f=fixture(url=>url.searchParams.get('alt')==='media'?new Response('x'.repeat(1048577),{headers:{'content-length':'1'}}):json(meta({size:undefined})));try{await assert.rejects(f.service.importSelected(account,{kind:'drive_file',resourceId:id}),{code:'response_invalid'});}finally{await f.service.close();}});
test('saved Gmail tokens cannot be used for Drive and profile failure does not disclose provider body',async()=>{const f=fixture();f.store.values.set('tokens',f.store.values.get('tokens')!.replace('drive.readonly','gmail.readonly'));try{await assert.rejects(f.service.verifyConnection(account),{code:'connection_expired'});assert.equal(f.calls.length,0);}finally{await f.service.close();}const s=new GoogleWorkspaceService({store:new Store(),openExternal:async()=>{},fetch:async()=>new Response('private provider information',{status:403})});try{await assert.rejects(s.verifyConnection(account),e=>e instanceof Error&&!e.message.includes('private provider'));assert.equal(s.verifiedConnectedAccount(),null);}finally{await s.close();}});
test('Drive consent uses its own exact scope, PKCE and profile identity without Gmail endpoints',async()=>{const store=new Store(),calls:string[]=[];let opened='';const service=new GoogleWorkspaceService({store,authorizationTimeoutMs:1000,openExternal:async url=>{opened=url;},fetch:async(input,init)=>{const url=String(input);calls.push(url);if(url==='https://oauth2.googleapis.com/token'){assert.equal(init?.method,'POST');assert.ok(String(init?.body).includes('code_verifier'));return json({access_token:'test-access',refresh_token:'test-refresh',expires_in:3600,scope:GOOGLE_WORKSPACE_SCOPE,token_type:'Bearer'});}assert.equal(url,'https://www.googleapis.com/drive/v3/about?fields=user(emailAddress)');return json({user:{emailAddress:account}});}});try{await service.importClient(JSON.stringify({installed:{client_id:'123.apps.googleusercontent.com',client_secret:'fixture',redirect_uris:['http://localhost']}}));await service.connect(account);const auth=new URL(opened);assert.equal(auth.searchParams.get('scope'),GOOGLE_WORKSPACE_SCOPE);assert.equal(auth.searchParams.get('code_challenge_method'),'S256');assert.equal(auth.searchParams.get('include_granted_scopes'),'false');assert.equal(auth.searchParams.has('client_secret'),false);const callback=new URL(auth.searchParams.get('redirect_uri')!);callback.searchParams.set('state',auth.searchParams.get('state')!);callback.searchParams.set('code','fixture-code');assert.equal((await fetch(callback)).status,200);for(let i=0;i<100&&!(await service.status()).connectedAccount;i++)await new Promise(r=>setTimeout(r,5));assert.equal((await service.status()).connectedAccount,account);assert.equal(service.verifiedConnectedAccount(),account);assert.equal(calls.length,2);assert.ok(calls.every(url=>!url.includes('gmail')));}finally{await service.close();}});
test('revoked persisted identity fails profile-only verification before any document request',async()=>{const calls:string[]=[],service=new GoogleWorkspaceService({store:new Store(),openExternal:async()=>{},fetch:async(input)=>{calls.push(String(input));return new Response('revoked-private-detail',{status:401});}});try{await assert.rejects(service.verifyConnection(account),{code:'connection_expired'});assert.equal(calls.length,1);assert.ok(calls[0].includes('/about'));assert.equal(service.verifiedConnectedAccount(),null);}finally{await service.close();}});
