import {GmailReviewService} from './review';
import {createHash,randomBytes,timingSafeEqual} from 'node:crypto';
import {createServer,type Server} from 'node:http';
import {GOOGLE_WORKSPACE_SCOPE} from '../contracts/google-workspace';
import {GMAIL_SCOPE,type GmailCommand,type GmailState,type GmailUnreadMessage,type GmailUnreadResult} from '../contracts/gmail';
export type GmailSecretKey='client'|'tokens';
export interface GmailSecretStore {read(key:GmailSecretKey):Promise<string|null>;write(key:GmailSecretKey,value:string):Promise<void>;remove(key:GmailSecretKey):Promise<void>}
export interface GmailOptions {store:GmailSecretStore;openExternal:(url:string)=>Promise<void>;fetch?:typeof fetch;now?:()=>number;onChanged?:()=>void;requestTimeoutMs?:number;authorizationTimeoutMs?:number;readTimeoutMs?:number;resource?:'gmail'|'drive'}
interface Client {clientId:string;clientSecret:string}
interface Tokens {account:string;accessToken:string;refreshToken:string;expiresAt:number;scope:typeof GMAIL_SCOPE|typeof GOOGLE_WORKSPACE_SCOPE}
const AUTH='https://accounts.google.com/o/oauth2/v2/auth',TOKEN='https://oauth2.googleapis.com/token',API='https://gmail.googleapis.com/gmail/v1/users/me';
const messages:Record<string,string>={selection_expired:'This selection expired or was not reviewed. Search again and select the thread or attachment.',review_too_large:'This thread exceeds the review limit. Select a smaller thread or import specific messages manually.',unsupported_content:'This content is not supported for safe text review or attachment import.',client_missing:'Import a Google Desktop OAuth client JSON in Gmail connection settings.',client_invalid:'Choose the JSON downloaded for a Google Desktop app OAuth client.',connection_missing:'Connect the exact requested Gmail account in settings.',account_mismatch:'Google returned a different account. No message contents were read; connect the requested account.',scope_denied:'Google did not grant the exact Gmail read-only scope.',access_denied:'Gmail access was declined. No connection was saved.',oauth_failed:'Google authorization could not complete. Check the Desktop client configuration and consent settings.',response_invalid:'Google returned an invalid or oversized response.',connection_expired:'Gmail authorization expired or was revoked. Connect the account again.',network_error:'The Gmail request could not complete. Existing unread status was preserved.',timeout:'The Gmail operation timed out. Try again when ready.',cancelled:'The Gmail operation was cancelled.',busy:'A Gmail operation is already in progress.',closed:'The Gmail service is closing.',keychain_unavailable:'The Gmail Keychain helper is unavailable or access was denied.',invalid_command:'The Gmail command is invalid.'};
export class GmailError extends Error {constructor(readonly code:string){super(messages[code]||messages.oauth_failed);this.name='GmailError';}}
function fail(code:string):never{throw new GmailError(code);}
function record(v:unknown):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||![Object.prototype,null].includes(Object.getPrototypeOf(v)))fail('response_invalid');return v as Record<string,unknown>;}
function string(v:unknown,max:number):string{if(typeof v!=='string'||!v||Buffer.byteLength(v)>max||/[\x00-\x1f\x7f]/.test(v))fail('response_invalid');return v;}
export function gmailAccount(v:unknown):string{if(typeof v!=='string'||v.length>254||!/^[-a-zA-Z0-9.!#$%&'*+/=?^_`{|}~]+@[a-zA-Z0-9](?:[a-zA-Z0-9.-]*[a-zA-Z0-9])?\.[a-zA-Z]{2,}$/.test(v))fail('invalid_command');return v.toLowerCase();}
export function parseGmailCommand(raw:unknown):GmailCommand{const v=record(raw);if(v.type==='gmail.state'||v.type==='gmail.disconnect'){if(Object.keys(v).length!==1)fail('invalid_command');return{type:v.type};}if(v.type==='gmail.connect'&&Object.keys(v).length===2&&Object.hasOwn(v,'account'))return{type:v.type,account:gmailAccount(v.account)};return fail('invalid_command');}
export function parseDesktopClient(json:string):Client {
 try{if(typeof json!=='string'||Buffer.byteLength(json)>16384)fail('client_invalid');const top=record(JSON.parse(json));if(Object.keys(top).length!==1||!top.installed)fail('client_invalid');const v=record(top.installed);
  const allowed=['client_id','client_secret','project_id','auth_uri','token_uri','auth_provider_x509_cert_url','redirect_uris'];if(Object.keys(v).some(k=>!allowed.includes(k)))fail('client_invalid');
  const clientId=string(v.client_id,256),clientSecret=string(v.client_secret,512);if(!/^[A-Za-z0-9_-]+\.apps\.googleusercontent\.com$/.test(clientId))fail('client_invalid');
  if(v.token_uri!==undefined&&v.token_uri!==TOKEN)fail('client_invalid');if(v.auth_uri!==undefined&&!['https://accounts.google.com/o/oauth2/auth',AUTH].includes(String(v.auth_uri)))fail('client_invalid');
  if(v.auth_provider_x509_cert_url!==undefined&&v.auth_provider_x509_cert_url!=='https://www.googleapis.com/oauth2/v1/certs')fail('client_invalid');
  if(!Array.isArray(v.redirect_uris)||!v.redirect_uris.length||v.redirect_uris.length>8||v.redirect_uris.some(uri=>!['http://localhost','http://localhost/','http://127.0.0.1','http://127.0.0.1/'].includes(String(uri))))fail('client_invalid');return{clientId,clientSecret};
 }catch{return fail('client_invalid');}
}
function savedTokens(raw:string|null,scope:string=GMAIL_SCOPE):Tokens|null {if(!raw)return null;try{if(Buffer.byteLength(raw)>16384)fail('response_invalid');const v=record(JSON.parse(raw));if(v.scope!==scope||typeof v.expiresAt!=='number'||!Number.isSafeInteger(v.expiresAt))fail('response_invalid');return{account:gmailAccount(v.account),accessToken:string(v.accessToken,4096),refreshToken:string(v.refreshToken,4096),expiresAt:v.expiresAt,scope:scope as Tokens['scope']};}catch{return fail('connection_expired');}}
function clean(value:unknown,max:number):string{if(typeof value!=='string')return'';return Array.from(value.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g,'')).slice(0,max).join('');}
/** Only the fixed Google OAuth/token and read-only Gmail endpoints are reachable through this API. */
export class GmailService {
 private reviewService?:GmailReviewService;
 private verifiedAccount:string|null=null;
 private generation=0;private closed=false;private configured=false;private account:string|null=null;private error:string|null=null;private connecting=false;private server?:Server;private oauthTimer?:ReturnType<typeof setTimeout>;private pending?:Promise<void>;private controls=new Set<AbortController>();private writes:Promise<unknown>=Promise.resolve();private mutation=false;private reading=false;
 constructor(private options:GmailOptions){}
 private scope(){return this.options.resource==='drive'?GOOGLE_WORKSPACE_SCOPE:GMAIL_SCOPE;}
 private now(){return(this.options.now||Date.now)();}
 private changed(){this.options.onChanged?.();}
 private guard(g:number){if(this.closed)fail('closed');if(g!==this.generation)fail('cancelled');}
 private view():GmailState{return{configured:this.configured,connectedAccount:this.account,connecting:this.connecting||!!this.pending,error:this.error};}
 private async storage<T>(fn:()=>Promise<T>):Promise<T>{const next=this.writes.catch(()=>undefined).then(fn);this.writes=next.catch(()=>undefined);return next;}
 private async client():Promise<Client>{const saved=await this.options.store.read('client');if(!saved)fail('client_missing');try{const v=record(JSON.parse(saved));return{clientId:string(v.clientId,256),clientSecret:string(v.clientSecret,512)};}catch{return fail('client_invalid');}}
 async status():Promise<GmailState>{if(this.closed)return{configured:false,connectedAccount:null,connecting:false,error:messages.closed};const generation=this.generation;try{const c=await this.options.store.read('client'),t=savedTokens(await this.options.store.read('tokens'),this.scope());if(this.closed||generation!==this.generation)return this.view();this.configured=!!c;this.account=c?t?.account||null:null;}catch(error){if(generation===this.generation){this.configured=false;this.account=null;this.error=error instanceof GmailError?error.message:messages.keychain_unavailable;}}return this.view();}
 async handle(raw:unknown):Promise<GmailState>{const command=parseGmailCommand(raw);return command.type==='gmail.state'?this.status():command.type==='gmail.connect'?this.connect(command.account):this.disconnect();}
 async importClient(json:string):Promise<GmailState>{const client=parseDesktopClient(json);if(this.closed)fail('closed');if(this.mutation)fail('busy');this.mutation=true;try{await this.cancel();await this.storage(async()=>{await this.options.store.remove('tokens');await this.options.store.write('client',JSON.stringify(client));});this.configured=true;this.account=null;this.error=null;this.changed();return this.view();}finally{this.mutation=false;}}
 private async cancel(){this.verifiedAccount=null;this.generation++;for(const controller of this.controls)controller.abort();clearTimeout(this.oauthTimer);this.oauthTimer=undefined;if(this.server){this.server.closeAllConnections();await new Promise<void>(resolve=>this.server!.close(()=>resolve()));this.server=undefined;}this.connecting=false;await this.pending?.catch(()=>undefined);await this.writes;}
 async disconnect():Promise<GmailState>{if(this.closed)fail('closed');if(this.mutation)fail('busy');this.mutation=true;try{await this.cancel();await this.storage(()=>this.options.store.remove('tokens'));this.account=null;this.error=null;this.changed();return this.view();}finally{this.mutation=false;}}
 async connect(rawAccount:string):Promise<GmailState>{const account=gmailAccount(rawAccount);if(this.closed)fail('closed');if(this.mutation||this.connecting||this.reading)fail('busy');this.mutation=true;
  try{const client=await this.client();if(this.closed)fail('closed');await this.cancel();if(this.closed)fail('closed');const generation=this.generation,state=randomBytes(32).toString('base64url'),verifier=randomBytes(32).toString('base64url'),challenge=createHash('sha256').update(verifier).digest('base64url');this.configured=true;this.connecting=true;this.error=null;
   let port=0,redirect='';const server=createServer({maxHeaderSize:8192},(req,res)=>{const headers={'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'none'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};const respond=(status:number,body:string)=>{res.writeHead(status,headers);res.end(body);};
    if(!this.connecting||generation!==this.generation||req.method!=='GET'||req.headers.host!==`127.0.0.1:${port}`||req.socket.remoteAddress!=='127.0.0.1'||!req.url||req.url.length>8192){respond(400,'Invalid authorization callback.');return;}
    let url:URL;try{url=new URL(req.url,redirect);}catch{respond(400,'Invalid authorization callback.');return;}
    const received=url.searchParams.get('state')||'';if(url.origin!==redirect.slice(0,-1)||url.pathname!=='/'||url.searchParams.getAll('state').length!==1||Buffer.byteLength(received)!==Buffer.byteLength(state)||!timingSafeEqual(Buffer.from(received),Buffer.from(state))){respond(400,'Invalid authorization callback.');return;}
    const code=url.searchParams.get('code'),error=url.searchParams.get('error');if((code&&error)||(!code&&!error)||url.searchParams.getAll('code').length>1||url.searchParams.getAll('error').length>1||code&&code.length>4096){respond(400,'Invalid authorization callback.');return;}
    // Consume the state once before any asynchronous exchange; never echo callback values.
    this.connecting=false;clearTimeout(this.oauthTimer);server.close();this.server=undefined;respond(200,'Authorization received. Return to Agent Workspaces to see the connection result.');
    const work=(async()=>{try{if(error)fail(error==='access_denied'?'access_denied':'oauth_failed');const token=await this.token(client,{grant_type:'authorization_code',code:code!,code_verifier:verifier,redirect_uri:redirect},generation);const profile=await this.profile(token.accessToken,generation);if(profile!==account)fail('account_mismatch');const saved={...token,account};await this.storage(async()=>{this.guard(generation);await this.options.store.write('tokens',JSON.stringify(saved));});this.guard(generation);this.account=account;this.verifiedAccount=account;this.error=null;}catch(cause){if(generation===this.generation)this.error=cause instanceof GmailError?cause.message:messages.oauth_failed;}finally{if(generation===this.generation)this.changed();}})();this.pending=work;void work.finally(()=>{if(this.pending===work)this.pending=undefined;});
   });server.requestTimeout=10000;server.headersTimeout=5000;server.maxConnections=8;this.server=server;
   await new Promise<void>((resolve,reject)=>{server.once('error',()=>reject(new GmailError('oauth_failed')));server.listen(0,'127.0.0.1',()=>resolve());});const address=server.address();if(!address||typeof address==='string')fail('oauth_failed');port=address.port;redirect=`http://127.0.0.1:${port}/`;
   this.oauthTimer=setTimeout(()=>{if(generation!==this.generation)return;this.connecting=false;this.error=messages.timeout;server.closeAllConnections();server.close();this.server=undefined;this.generation++;this.changed();},this.options.authorizationTimeoutMs??180000);
   const url=new URL(AUTH);for(const [key,value]of Object.entries({client_id:client.clientId,redirect_uri:redirect,response_type:'code',scope:this.scope(),state,code_challenge:challenge,code_challenge_method:'S256',login_hint:account,prompt:'consent select_account',access_type:'offline',include_granted_scopes:'false'}))url.searchParams.set(key,value);
   try{await this.options.openExternal(url.href);}catch{await this.cancel();this.error=messages.oauth_failed;fail('oauth_failed');}this.changed();return this.view();
  }catch(cause){if(this.server)await this.cancel();throw cause;}finally{this.mutation=false;}
 }
 private async responseBytes(url:string,init:RequestInit,generation:number,outer?:AbortSignal,maxBytes=262144):Promise<Buffer>{
  this.guard(generation);if(outer?.aborted)fail('cancelled');const controller=new AbortController();this.controls.add(controller);const abort=()=>controller.abort();outer?.addEventListener('abort',abort,{once:true});let timer:ReturnType<typeof setTimeout>|undefined;
  const stopped=new Promise<never>((_,reject)=>{controller.signal.addEventListener('abort',()=>reject(new GmailError(outer?.aborted||generation!==this.generation||this.closed?'cancelled':'timeout')),{once:true});timer=setTimeout(abort,this.options.requestTimeoutMs??15000);});
  let readerRef:ReadableStreamDefaultReader<Uint8Array>|undefined;controller.signal.addEventListener('abort',()=>{void readerRef?.cancel().catch(()=>undefined);},{once:true});
  const operation=(async()=>{const response=await(this.options.fetch||fetch)(url,{...init,redirect:'error',signal:controller.signal});if(controller.signal.aborted){await response.body?.cancel().catch(()=>undefined);fail('cancelled');}if(!response.ok){await response.body?.cancel().catch(()=>undefined);if(response.status===401||response.status===400&&url===TOKEN)fail('connection_expired');if(response.status===403)fail('scope_denied');fail('network_error');}if(Number(response.headers.get('content-length'))>maxBytes){await response.body?.cancel().catch(()=>undefined);fail('response_invalid');}if(!response.body)fail('response_invalid');const reader=response.body.getReader();readerRef=reader;const chunks:Uint8Array[]=[];let bytes=0;try{while(true){const r=await reader.read();if(r.done)break;bytes+=r.value.length;if(bytes>maxBytes)fail('response_invalid');chunks.push(r.value);if(controller.signal.aborted)fail('cancelled');}return Buffer.concat(chunks);}finally{await reader.cancel().catch(()=>undefined);}})();
  try{const result=await Promise.race([operation,stopped]);this.guard(generation);if(outer?.aborted)fail('cancelled');return result;}catch(error){if(error instanceof GmailError)throw error;return fail('network_error');}finally{clearTimeout(timer);this.controls.delete(controller);outer?.removeEventListener('abort',abort);controller.abort();}
 }
 private async json(url:string,init:RequestInit,generation:number,outer?:AbortSignal,maxBytes=262144):Promise<Record<string,unknown>>{const bytes=await this.responseBytes(url,init,generation,outer,maxBytes);try{return record(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes)));}catch{fail('response_invalid');}finally{bytes.fill(0);}}
 private async token(client:Client,params:Record<string,string>,generation:number,prior?:Tokens,signal?:AbortSignal):Promise<Omit<Tokens,'account'>>{
  const response=await this.json(TOKEN,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:client.clientId,client_secret:client.clientSecret,...params})},generation,signal,32768);
  if(response.token_type!=='Bearer'||(response.scope===undefined?prior?.scope:response.scope)!==this.scope())fail('scope_denied');const seconds=Number(response.expires_in);if(!Number.isSafeInteger(seconds)||seconds<1||seconds>86400)fail('response_invalid');return{accessToken:string(response.access_token,4096),refreshToken:response.refresh_token===undefined&&prior?prior.refreshToken:string(response.refresh_token,4096),expiresAt:this.now()+seconds*1000,scope:this.scope()};
 }
 private async profile(token:string,generation:number,signal?:AbortSignal){const drive=this.options.resource==='drive';const result=await this.json(drive?'https://www.googleapis.com/drive/v3/about?fields=user(emailAddress)':`${API}/profile?fields=emailAddress`,{method:'GET',headers:{Authorization:`Bearer ${token}`}},generation,signal,16384);return gmailAccount(drive?record(result.user).emailAddress:result.emailAddress);}
 async readUnread(rawAccount:string,{signal}:{signal?:AbortSignal}={}):Promise<GmailUnreadResult>{if(this.options.resource==='drive')fail('invalid_command');const account=gmailAccount(rawAccount);if(this.closed)fail('closed');if(this.reading||this.connecting||this.mutation||this.pending)fail('busy');if(signal?.aborted)fail('cancelled');this.reading=true;this.verifiedAccount=null;const generation=this.generation,controller=new AbortController(),abort=()=>controller.abort();this.controls.add(controller);signal?.addEventListener('abort',abort,{once:true});const timer=setTimeout(abort,this.options.readTimeoutMs??60000);
  try{const client=await this.client();let token=savedTokens(await this.options.store.read('tokens'),this.scope());this.guard(generation);if(!token)fail('connection_missing');if(token.account!==account)fail('account_mismatch');
   if(token.expiresAt<=this.now()+30000){token={...await this.token(client,{grant_type:'refresh_token',refresh_token:token.refreshToken},generation,token,controller.signal),account};await this.storage(async()=>{this.guard(generation);await this.options.store.write('tokens',JSON.stringify(token));});}
   const verified=await this.profile(token.accessToken,generation,controller.signal);if(verified!==account)fail('account_mismatch');this.verifiedAccount=account;const headers={Authorization:`Bearer ${token.accessToken}`};const list=await this.json(`${API}/messages?labelIds=UNREAD&maxResults=50&includeSpamTrash=false&fields=messages(id,threadId),nextPageToken,resultSizeEstimate`,{method:'GET',headers},generation,controller.signal,32768);
   if(list.messages!==undefined&&!Array.isArray(list.messages)||Array.isArray(list.messages)&&list.messages.length>50)fail('response_invalid');const refs=(list.messages||[]) as unknown[];let metadataClipped=false;const seen=new Set<string>(),messages:GmailUnreadMessage[]=[];
   for(const ref of refs){const id=string(record(ref).id,128);if(!/^[A-Za-z0-9_-]+$/.test(id)||seen.has(id))fail('response_invalid');seen.add(id);const url=new URL(`${API}/messages/${id}`);url.searchParams.set('format','metadata');for(const name of ['From','To','Subject','Date'])url.searchParams.append('metadataHeaders',name);url.searchParams.set('fields','id,threadId,labelIds,snippet,payload/headers');const message=await this.json(url.href,{method:'GET',headers},generation,controller.signal,65536);
    if(message.id!==id||!Array.isArray(message.labelIds)||!message.labelIds.includes('UNREAD'))continue;const payload=record(message.payload||{}),list=payload.headers;if(list!==undefined&&(!Array.isArray(list)||list.length>64))fail('response_invalid');const field=(value:unknown,max:number)=>{if(typeof value==='string'&&Array.from(value).length>max)metadataClipped=true;return clean(value,max);};const get=(name:string)=>field((list as unknown[]||[]).map(record).find(h=>typeof h.name==='string'&&h.name.toLowerCase()===name)?.value,512);const threadId=string(message.threadId,128);if(!/^[A-Za-z0-9_-]+$/.test(threadId))fail('response_invalid');messages.push({id,threadId,from:get('from'),to:get('to'),subject:get('subject'),date:get('date'),snippet:field(message.snippet,1024)});
   }
   this.guard(generation);if(controller.signal.aborted)fail('cancelled');const result:GmailUnreadResult={source:'gmail_readonly_api',account,accountVerified:true,listingVerified:true,query:'is:unread',messages,hasMore:typeof list.nextPageToken==='string'&&!!list.nextPageToken,resultSizeEstimate:Number.isSafeInteger(list.resultSizeEstimate)&&Number(list.resultSizeEstimate)>=0?Number(list.resultSizeEstimate):null,preservedUnread:true,summariesTruncated:metadataClipped,retrievedAt:this.now()};
   // Keep all <=50 result identities and the verified account envelope inside the live tool receipt bound.
   while(Buffer.byteLength(JSON.stringify(result))>22000){let largest:{message:GmailUnreadMessage;key:'from'|'to'|'subject'|'date'|'snippet';bytes:number}|undefined;for(const message of messages)for(const key of ['from','to','subject','date','snippet'] as const){const bytes=Buffer.byteLength(message[key]);if(bytes&&(!largest||bytes>largest.bytes))largest={message,key,bytes};}if(!largest)fail('response_invalid');const points=Array.from(largest.message[largest.key]);largest.message[largest.key]=points.slice(0,Math.floor(points.length/2)).join('');result.summariesTruncated=true;}
   return result;
  }finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);this.controls.delete(controller);controller.abort();this.reading=false;}
 }
 /** Backend-only read session. The callback receives bounded GET helpers, never credentials.
  * Callers must resolve project/account and resource authority before invoking it. */
 async readSelectedSession<T>(rawAccount:string,work:(session:ReadonlyGoogleSession)=>Promise<T>,{signal}:{signal?:AbortSignal}={}):Promise<T>{
  const account=gmailAccount(rawAccount);if(this.closed)fail('closed');if(this.reading||this.connecting||this.mutation||this.pending)fail('busy');if(signal?.aborted)fail('cancelled');this.reading=true;this.verifiedAccount=null;
  const generation=this.generation,controller=new AbortController(),abort=()=>controller.abort();this.controls.add(controller);signal?.addEventListener('abort',abort,{once:true});const timer=setTimeout(abort,this.options.readTimeoutMs??60000);
  try{const client=await this.client();let token=savedTokens(await this.options.store.read('tokens'),this.scope());this.guard(generation);if(!token)fail('connection_missing');if(token.account!==account)fail('account_mismatch');
   if(token.expiresAt<=this.now()+30000){token={...await this.token(client,{grant_type:'refresh_token',refresh_token:token.refreshToken},generation,token,controller.signal),account};await this.storage(async()=>{this.guard(generation);await this.options.store.write('tokens',JSON.stringify(token));});}
   if(await this.profile(token.accessToken,generation,controller.signal)!==account)fail('account_mismatch');this.verifiedAccount=account;const headers={Authorization:`Bearer ${token.accessToken}`};
   const check=(raw:string,max:number)=>{if(!Number.isSafeInteger(max)||max<1||max>8*1024*1024)fail('invalid_command');const url=new URL(raw);if(url.username||url.password||url.hash)fail('invalid_command');const allowed=this.options.resource==='drive'?(url.origin==='https://www.googleapis.com'&&/^\/drive\/v3\/files\/[A-Za-z0-9_-]+(?:\/export)?$/.test(url.pathname)||url.origin==='https://sheets.googleapis.com'&&/^\/v4\/spreadsheets\/[A-Za-z0-9_-]+\/values\/[^/]+$/.test(url.pathname)):(url.origin==='https://gmail.googleapis.com'&&/^\/gmail\/v1\/users\/me\/(?:messages(?:\/[A-Za-z0-9_-]+(?:\/attachments\/[A-Za-z0-9_-]+)?)?|threads\/[A-Za-z0-9_-]+)$/.test(url.pathname));if(!allowed)fail('invalid_command');return url.href;};
   const result=await work({generation,now:()=>this.now(),json:(url,max=262144)=>this.json(check(url,max),{method:'GET',headers},generation,controller.signal,max),bytes:(url,max)=>this.responseBytes(check(url,max),{method:'GET',headers},generation,controller.signal,max)});this.guard(generation);if(controller.signal.aborted)fail('cancelled');return result;
  }finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);this.controls.delete(controller);controller.abort();this.reading=false;}
 }
 async verifyConnection(account:string,{signal}:{signal?:AbortSignal}={}){const normalized=gmailAccount(account);return this.readSelectedSession(normalized,async s=>({account:normalized,accountVerified:true as const,checkedAt:s.now(),readOnly:true as const}),{signal});}
 searchReadonly(...args:Parameters<GmailReviewService['searchReadonly']>){if(this.options.resource==='drive')fail('invalid_command');return(this.reviewService??=new GmailReviewService(this)).searchReadonly(...args);}
 readThreadReadonly(...args:Parameters<GmailReviewService['readThreadReadonly']>){if(this.options.resource==='drive')fail('invalid_command');return(this.reviewService??=new GmailReviewService(this)).readThreadReadonly(...args);}
 readAttachmentReadonly(...args:Parameters<GmailReviewService['readAttachmentReadonly']>){if(this.options.resource==='drive')fail('invalid_command');return(this.reviewService??=new GmailReviewService(this)).readAttachmentReadonly(...args);}
 verifiedConnectedAccount(){return this.closed?null:this.verifiedAccount;}
 async close(){if(this.closed)return;this.closed=true;await this.cancel();}
}

export interface ReadonlyGoogleSession {generation:number;now:()=>number;json:(url:string,maxBytes?:number)=>Promise<Record<string,unknown>>;bytes:(url:string,maxBytes:number)=>Promise<Buffer>}
