import {createHash,randomUUID} from 'node:crypto';
import {GmailError,gmailAccount,type GmailService,type ReadonlyGoogleSession} from './index';
import type {GmailUnreadMessage} from '../contracts/gmail';
import type {GmailSearchPage,GmailThreadResult,GmailThreadMessage,GmailAttachmentRef,GmailAttachmentReceipt,GmailReviewCommand} from '../contracts/gmail-review';
const API='https://gmail.googleapis.com/gmail/v1/users/me',TTL=5*60*1000,MAX_ATTACHMENT=1024*1024;
function fail(code='response_invalid'):never{throw new GmailError(code);}
function record(v:unknown):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||![Object.prototype,null].includes(Object.getPrototypeOf(v)))fail();return v as Record<string,unknown>;}
function id(v:unknown,max=256){if(typeof v!=='string'||!new RegExp(`^[A-Za-z0-9_-]{1,${max}}$`).test(v))fail('invalid_command');return v;}
function clean(v:unknown,max:number){return typeof v==='string'?v.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g,'').slice(0,max):'';}
function query(v:unknown){if(typeof v!=='string'||!v.trim()||Buffer.byteLength(v)>512||/[\x00-\x1f\x7f]/.test(v))fail('invalid_command');return v.trim();}
function metadata(raw:Record<string,unknown>):GmailUnreadMessage{const payload=record(raw.payload||{});if(payload.headers!==undefined&&(!Array.isArray(payload.headers)||payload.headers.length>128))fail();const headers=(payload.headers||[]) as unknown[];const get=(name:string)=>clean(headers.map(record).find(h=>typeof h.name==='string'&&h.name.toLowerCase()===name)?.value,256);return{id:id(raw.id),threadId:id(raw.threadId),from:get('from'),to:get('to'),subject:get('subject'),date:get('date'),snippet:clean(raw.snippet,512)};}
function decode(raw:unknown,size:number):Buffer{if(typeof raw!=='string'||raw.length>Math.ceil(size/3)*4+4||!/^[-_A-Za-z0-9]*={0,2}$/.test(raw))fail();const bytes=Buffer.from(raw,'base64url');if(bytes.length>size||bytes.toString('base64url')!==raw.replace(/=+$/,''))fail();return bytes;}
const formats:Record<string,string>={'text/plain':'txt','text/csv':'csv','text/markdown':'md','application/json':'json','application/pdf':'pdf'};
function attachmentName(raw:unknown,mime:string){const ext=formats[mime],value=clean(raw,200).replace(/[/\\:]/g,'_').trim();if(!value||!ext||!value.toLowerCase().endsWith('.'+ext))return null;return value;}
interface Timed {account:string;generation:number;expires:number}
interface Cursor extends Timed {query:string;providerToken:string;page:number;seen:string[]}
interface Attachment extends Timed {ref:GmailAttachmentRef}
export function parseGmailReviewCommand(raw:unknown):GmailReviewCommand{const v=record(raw),taskId=id(v.taskId,128);if(v.type==='gmailReview.search'&&Object.keys(v).every(k=>['type','taskId','query','cursor'].includes(k)))return{type:v.type,taskId,query:query(v.query),...(v.cursor!==undefined?{cursor:id(v.cursor,128)}:{})};if(v.type==='gmailReview.thread'&&Object.keys(v).length===3)return{type:v.type,taskId,threadId:id(v.threadId)};if(v.type==='gmailReview.attachment'&&Object.keys(v).length===4)return{type:v.type,taskId,messageId:id(v.messageId),attachmentId:id(v.attachmentId)};return fail('invalid_command');}
/** New explicit review surface; the original unread-snippet tool does not call these methods. */
export class GmailReviewService {
 private cursors=new Map<string,Cursor>();private threads=new Map<string,Timed>();private attachments=new Map<string,Attachment>();
 constructor(private connection:GmailService){}
 private trim(session:ReadonlyGoogleSession){for(const map of [this.cursors,this.threads,this.attachments]){for(const[k,v]of map)if(v.expires<session.now()||v.generation!==session.generation)map.delete(k);while(map.size>100)map.delete(map.keys().next().value!);}}
 private valid(v:Timed|undefined,account:string,s:ReadonlyGoogleSession){return !!v&&v.account===account&&v.generation===s.generation&&v.expires>=s.now();}
 async searchReadonly(rawAccount:string,input:{query:string;cursor?:string},{signal}:{signal?:AbortSignal}={}):Promise<GmailSearchPage>{const account=gmailAccount(rawAccount),q=query(input.query);if(input.cursor!==undefined)id(input.cursor,128);return this.connection.readSelectedSession(account,async s=>{this.trim(s);const prior=input.cursor?this.cursors.get(input.cursor):undefined;if(input.cursor&&(!this.valid(prior,account,s)||prior!.query!==q))fail('invalid_command');if(input.cursor)this.cursors.delete(input.cursor);const page=prior?.page||1,url=new URL(`${API}/messages`);for(const[k,v]of Object.entries({q,maxResults:'20',includeSpamTrash:'false',fields:'messages(id,threadId),nextPageToken,resultSizeEstimate'}))url.searchParams.set(k,v);if(prior)url.searchParams.set('pageToken',prior.providerToken);const result=await s.json(url.href,32768);if(result.messages!==undefined&&(!Array.isArray(result.messages)||result.messages.length>20))fail();const seen=new Set(prior?.seen||[]),messages:GmailUnreadMessage[]=[],selectedThreads:string[]=[];for(const item of (result.messages||[]) as unknown[]){const ref=record(item),messageId=id(ref.id),threadId=id(ref.threadId);if(seen.has(messageId))continue;seen.add(messageId);const url=new URL(`${API}/messages/${messageId}`);url.searchParams.set('format','metadata');url.searchParams.set('fields','id,threadId,snippet,payload/headers');for(const name of ['From','To','Subject','Date'])url.searchParams.append('metadataHeaders',name);const raw=await s.json(url.href,32768);if(raw.id!==messageId||raw.threadId!==threadId)fail();messages.push(metadata(raw));selectedThreads.push(threadId);}
 const token=result.nextPageToken;if(token!==undefined&&(typeof token!=='string'||!token||token.length>2048||/[\x00-\x1f\x7f]/.test(token)))fail();let nextCursor:string|null=null;if(token&&page<5){nextCursor=randomUUID();this.cursors.set(nextCursor,{account,generation:s.generation,expires:s.now()+TTL,query:q,providerToken:String(token),page:page+1,seen:[...seen]});}const resultPage:GmailSearchPage={source:'gmail_readonly_api',account,accountVerified:true,query:q,messages,nextCursor,hasMore:!!token,page,pageLimit:5,pageSize:20,resultSizeEstimate:Number.isSafeInteger(result.resultSizeEstimate)&&Number(result.resultSizeEstimate)>=0?Number(result.resultSizeEstimate):null,coverage:'bounded_search',summariesTruncated:false,preservedUnread:true,retrievedAt:s.now()};while(Buffer.byteLength(JSON.stringify(resultPage))>22000){const candidates=messages.flatMap(message=>(['from','to','subject','date','snippet'] as const).map(key=>({message,key}))).filter(v=>v.message[v.key].length).sort((a,b)=>Buffer.byteLength(b.message[b.key])-Buffer.byteLength(a.message[a.key]));const largest=candidates[0];if(!largest)fail('review_too_large');largest.message[largest.key]=Array.from(largest.message[largest.key]).slice(0,Math.floor(Array.from(largest.message[largest.key]).length/2)).join('');resultPage.summariesTruncated=true;}for(const threadId of selectedThreads)this.threads.set(account+':'+threadId,{account,generation:s.generation,expires:s.now()+TTL});this.trim(s);return resultPage;},{signal});}
 async readThreadReadonly(rawAccount:string,input:{threadId:string},{signal}:{signal?:AbortSignal}={}):Promise<GmailThreadResult>{const account=gmailAccount(rawAccount),threadId=id(input.threadId);return this.connection.readSelectedSession(account,async s=>{this.trim(s);if(!this.valid(this.threads.get(account+':'+threadId),account,s))fail('selection_expired');const url=new URL(`${API}/threads/${threadId}`);url.searchParams.set('format','full');url.searchParams.set('fields','id,messages(id,threadId,snippet,payload)');const raw=await s.json(url.href,1024*1024);if(raw.id!==threadId||!Array.isArray(raw.messages)||!raw.messages.length||raw.messages.length>20)fail('review_too_large');const messages:GmailThreadMessage[]=[],seen=new Set<string>(),selectedAttachments:Attachment[]=[];let remaining=12000,partsSeen=0;
 for(const value of raw.messages){const valueRecord=record(value),base=metadata(valueRecord);if(base.threadId!==threadId||seen.has(base.id))fail();seen.add(base.id);let body='',bodyTruncated=false,htmlOmitted=false,bodyUnavailable=false;const attachments:GmailAttachmentRef[]=[];
 const walk=(value:unknown,depth:number)=>{if(depth>8||++partsSeen>128)fail('review_too_large');const part=record(value),mime=typeof part.mimeType==='string'?part.mimeType.toLowerCase():'',partBody=record(part.body||{}),name=clean(part.filename,200);if(name){const attachmentId=partBody.attachmentId,size=partBody.size;if(attachmentId!==undefined){id(attachmentId);if(!Number.isSafeInteger(size)||Number(size)<0)fail();const safe=attachmentName(name,mime),ref:GmailAttachmentRef={messageId:base.id,attachmentId:String(attachmentId),filename:name,mime:clean(mime,100),bytes:Number(size),importable:!!safe&&Number(size)>0&&Number(size)<=MAX_ATTACHMENT};attachments.push(ref);if(ref.importable)selectedAttachments.push({account,generation:s.generation,expires:s.now()+TTL,ref:{...ref,filename:safe!}});}}
 else if(mime==='text/plain'&&partBody.data!==undefined){const bytes=decode(partBody.data,512*1024);let text:string;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{fail('unsupported_content');}finally{bytes.fill(0);}const cleaned=clean(text,512*1024),budget=Math.max(0,Math.min(remaining,12000-body.length));if(cleaned.length>budget)bodyTruncated=true;body+=cleaned.slice(0,budget);remaining-=Math.min(cleaned.length,budget);}
 else if(mime==='text/html'){htmlOmitted=true;}else if(mime==='text/plain'&&partBody.attachmentId!==undefined){bodyUnavailable=true;}
 if(part.parts!==undefined){if(!Array.isArray(part.parts)||part.parts.length>64)fail();for(const child of part.parts)walk(child,depth+1);}};walk(valueRecord.payload||{},0);messages.push({...base,body,bodyFormat:'plain_text',bodyTruncated,htmlOmitted,bodyUnavailable:bodyUnavailable||!body,attachments});}
 this.trim(s);const result:GmailThreadResult={source:'gmail_readonly_api',account,accountVerified:true,threadId,messages,coverage:'selected_thread',bodyTruncated:messages.some(m=>m.bodyTruncated),headersTruncated:false,preservedUnread:true,retrievedAt:s.now(),notes:['Read only: no message was sent, modified, archived, or marked read.','HTML bodies, remote images, and embedded content are omitted. Attachments require separate selection.']};while(Buffer.byteLength(JSON.stringify(result))>22000){const bodies=messages.filter(m=>m.body).sort((a,b)=>Buffer.byteLength(b.body)-Buffer.byteLength(a.body));if(bodies[0]){const m=bodies[0];m.body=Array.from(m.body).slice(0,Math.floor(Array.from(m.body).length/2)).join('');m.bodyTruncated=true;result.bodyTruncated=true;continue;}const candidates=messages.flatMap(message=>(['from','to','subject','date','snippet'] as const).map(key=>({message,key}))).filter(v=>v.message[v.key].length).sort((a,b)=>Buffer.byteLength(b.message[b.key])-Buffer.byteLength(a.message[a.key]));const largest=candidates[0];if(!largest)fail('review_too_large');largest.message[largest.key]=Array.from(largest.message[largest.key]).slice(0,Math.floor(Array.from(largest.message[largest.key]).length/2)).join('');result.headersTruncated=true;}for(const selected of selectedAttachments)this.attachments.set(account+':'+selected.ref.messageId+':'+selected.ref.attachmentId,selected);this.trim(s);return result;},{signal});}
 async readAttachmentReadonly(rawAccount:string,input:{messageId:string;attachmentId:string},{signal}:{signal?:AbortSignal}={}):Promise<{filename:string;mime:string;bytes:Buffer;source:GmailAttachmentReceipt}>{const account=gmailAccount(rawAccount),messageId=id(input.messageId),attachmentId=id(input.attachmentId);return this.connection.readSelectedSession(account,async s=>{this.trim(s);const cached=this.attachments.get(account+':'+messageId+':'+attachmentId);if(!this.valid(cached,account,s)||!cached!.ref.importable)fail('selection_expired');const ref=cached!.ref,result=await s.json(`${API}/messages/${messageId}/attachments/${attachmentId}`,Math.ceil(MAX_ATTACHMENT/3)*4+4096);if(result.size!==ref.bytes)fail();const bytes=decode(result.data,MAX_ATTACHMENT);try{if(bytes.length!==ref.bytes)fail();if(ref.mime==='application/pdf'){if(bytes.subarray(0,5).toString()!=='%PDF-')fail('unsupported_content');}else{const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(text.includes('\0'))fail('unsupported_content');if(ref.mime==='application/json')JSON.parse(text);}return{filename:ref.filename,mime:ref.mime,bytes,source:{source:'gmail_attachment',account,accountVerified:true,messageId,attachmentId,filename:ref.filename,mime:ref.mime,sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,retrievedAt:s.now(),preservedUnread:true}};}catch(error){bytes.fill(0);if(error instanceof GmailError)throw error;return fail('unsupported_content');}},{signal});}
}
