import {useCallback,useEffect,useRef,useState} from 'react';
import type {AppBridge,Snapshot} from '../../../packages/contracts';
import type {GoogleWorkspaceState,GoogleWorkspaceCommand} from '../../../packages/contracts/google-workspace';
import type {ProjectsController} from './Projects';
import {GoogleWorkspacePanel} from './GoogleWorkspace';
export function Connections({bridge,snapshot,projects}:{bridge:AppBridge;snapshot:Snapshot;projects:ProjectsController}){
 const [state,setState]=useState<GoogleWorkspaceState|null>(null),[error,setError]=useState<string|null>(null);const alive=useRef(true),sequence=useRef(0),mutation=useRef(false),reading=useRef(false),refreshAgain=useRef(false),projectRefresh=useRef(projects.refresh);projectRefresh.current=projects.refresh;
 const refresh=useCallback(async():Promise<void>=>{if(!alive.current)return;if(mutation.current||reading.current){refreshAgain.current=true;return;}reading.current=true;refreshAgain.current=false;const ticket=++sequence.current;try{const result=await bridge.googleWorkspace({type:'googleWorkspace.state'});if(alive.current&&ticket===sequence.current){setState(result.state);setError(null);}}catch{if(alive.current&&ticket===sequence.current)setError('Google connection status is unavailable. Refresh to try again.');}finally{reading.current=false;if(alive.current&&refreshAgain.current&&!mutation.current)void refresh();}},[bridge]);
 useEffect(()=>{alive.current=true;void refresh();const off=bridge.onGoogleWorkspaceChanged(()=>void refresh());return()=>{alive.current=false;sequence.current++;off();};},[bridge,refresh]);
 const operation=async<T extends {state:GoogleWorkspaceState}>(work:()=>Promise<T>):Promise<T>=>{if(mutation.current)throw new Error('A Google connection action is already in progress.');mutation.current=true;const ticket=++sequence.current;try{const result=await work();if(alive.current&&ticket===sequence.current){setState(result.state);setError(null);}void projectRefresh.current();return result;}finally{mutation.current=false;if(alive.current&&refreshAgain.current)void refresh();}};
 const action=(command:GoogleWorkspaceCommand)=>operation(()=>bridge.googleWorkspace(command));
 return <GoogleWorkspacePanel state={state} statusError={error} projects={projects.state?.projects||[]} agents={snapshot.agents} onImportClient={async()=>{await operation(()=>bridge.googleWorkspaceImportClient());}} onConnect={async(projectId,account)=>{await action({type:'googleWorkspace.connect',projectId,account});}} onVerify={async()=>{await action({type:'googleWorkspace.verify'});}} onDisconnect={async()=>{await action({type:'googleWorkspace.disconnect'});}} onRefresh={refresh} onBind={async(projectId,account)=>{const result=await projects.perform({type:'projects.google_workspace.bind',projectId,account});if(!result)throw new Error('Project account approval failed. Refresh and try again.');}} onImport={async(projectId,agentId,selection)=>{const result=await action({type:'googleWorkspace.import',projectId,agentId,selection});if(!result.imported)throw new Error('No input was imported.');return result.imported;}}/>;
}
