import {useEffect,useRef,useState} from 'react';
import type {GoogleImportResult,GoogleSelection,GoogleWorkspaceState} from '../../../packages/contracts/google-workspace';
import type {ProjectSpace} from '../../../packages/contracts/projects';
import './google-workspace.css';
export interface GoogleWorkspacePanelProps {
 state:GoogleWorkspaceState|null;statusError?:string|null;projects:ProjectSpace[];agents:{id:string;name:string}[];
 onImportClient:()=>Promise<void>;onConnect:(projectId:string,account:string)=>Promise<void>;onVerify:()=>Promise<void>;onDisconnect:()=>Promise<void>;onRefresh:()=>Promise<void>;
 onBind?:(projectId:string,account:string)=>Promise<void>;
 onImport:(projectId:string,agentId:string,selection:GoogleSelection)=>Promise<GoogleImportResult>;
}
/** Owner-only selected imports; the renderer never receives tokens, bytes, or filesystem paths. */
export function GoogleWorkspacePanel({state,statusError,projects,agents,onImportClient,onConnect,onVerify,onDisconnect,onRefresh,onBind,onImport}:GoogleWorkspacePanelProps){
 const [projectId,setProjectId]=useState(''),[agentId,setAgentId]=useState(''),[account,setAccount]=useState(''),[kind,setKind]=useState<'drive_file'|'sheet_range'>('drive_file'),[resource,setResource]=useState(''),[range,setRange]=useState('Sheet1!A1:H100'),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<GoogleImportResult|null>(null);const alive=useRef(true),lock=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const project=projects.find(p=>p.id===projectId)||(!projectId?projects[0]:undefined),available=agents.filter(a=>project?.agentIds.includes(a.id)),agent=available.find(a=>a.id===agentId)||(!agentId?available[0]:undefined),bound=project?.googleWorkspaceAccount,connected=!!state?.connectedAccount&&state.connectedAccount===bound;
 const run=async(work:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{await work();}catch(e){if(alive.current)setError(e instanceof Error?e.message:'The Google action did not finish. Refresh the connection and try again.');}finally{lock.current=false;if(alive.current)setBusy(false);}};
 const disabled=busy||!!state?.connecting;
 return <section className="google-workspace-panel" aria-label="Selected Google Drive and Sheets inputs"><header><div><span className="eyebrow">SELECTED INPUTS</span><h2>Google Drive & Sheets</h2><p>Import one file or a chosen sheet range into an agent’s private files.</p></div><span className="model-status-chip">{state?.connecting?'Waiting for consent':state?.liveAccessTested?'Account verified':state?.connectedAccount?'Saved · verify account':state?.configured?'Ready to connect':state?'Setup needed':'Checking connection…'}</span></header>
 {(error||statusError||state?.error)&&<div className="agent-run-error" role="alert">{error||statusError||state?.error}</div>}
 <div className="google-input-grid"><label>Project<select value={project?.id||''} disabled={disabled} onChange={e=>{setProjectId(e.target.value);setAgentId('');setAccount('');setResult(null);}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Private destination<select value={agent?.id||''} disabled={disabled} onChange={e=>{setAgentId(e.target.value);setResult(null);}}>{available.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div>
 <p className="google-input-note">Project account: <strong>{bound||'Not bound yet'}</strong>. {state?.connectedAccount&&<>Saved connection: <strong>{state.connectedAccount}</strong>.</>}</p>
 <div className="google-input-grid"><label>Google account to connect<input type="email" value={account||bound||''} disabled={disabled||!!bound} maxLength={254} placeholder="you@example.com" onChange={e=>setAccount(e.target.value)} autoComplete="off" spellCheck={false}/></label><div className="google-connection-buttons"><button className="button small" disabled={disabled||!state} onClick={()=>void run(onImportClient)}>{state?.configured?'Replace client JSON':'Import Desktop client JSON'}</button><button className="button small" disabled={disabled||!state?.configured||!project||!(account||bound)} onClick={()=>void run(()=>onConnect(project!.id,account||bound!))}>Connect account</button>{state?.connectedAccount&&<button className="button small" disabled={disabled} onClick={()=>void run(onVerify)}>Verify account</button>}</div></div>
 {onBind&&state?.liveAccessTested&&state.connectedAccount&&project&&!bound&&<button className="button small" disabled={disabled} onClick={()=>void run(()=>onBind(project.id,state.connectedAccount!))}>Use verified {state.connectedAccount} for {project.name}</button>}
 <details className="google-setup"><summary>Connection setup and access</summary><p>This build uses your own Google Desktop OAuth client. Enable the Drive and Sheets APIs, configure Google consent and the test user, then import the downloaded Desktop client JSON through the file picker.</p><p>Google’s read-only Drive scope grants this connection access to read and download Drive files. Agent Workspaces limits this feature to the exact file or range you select here. It does not browse all files, edit a document, change sharing, or sync in the background.</p><p>A ready-to-use application-managed Google connection still needs external OAuth configuration and verification. Importing a client does not establish a tested connection.</p></details>
 <form onSubmit={e=>{e.preventDefault();if(!project||!agent||!connected)return;void run(async()=>{const next=await onImport(project.id,agent.id,kind==='drive_file'?{kind,resourceId:resource}:{kind,resourceId:resource,range});if(alive.current)setResult(next);});}}><div className="google-input-grid"><label>Input type<select value={kind} disabled={disabled} onChange={e=>{setKind(e.target.value as typeof kind);setResult(null);}}><option value="drive_file">Drive file or Google Doc</option><option value="sheet_range">Selected sheet range</option></select></label><label>File link or ID<input required value={resource} disabled={disabled} maxLength={2048} placeholder="Paste the selected Google file’s link" onChange={e=>{setResource(e.target.value);setResult(null);}} autoComplete="off"/></label></div>{kind==='sheet_range'&&<label>Named sheet and range<input required value={range} maxLength={256} disabled={disabled} onChange={e=>setRange(e.target.value)} placeholder="Sheet1!A1:H100"/><small>At most 1,000 rows, 32 columns, and 20,000 cells. Date cells may be imported as serial numbers.</small></label>}<p className="google-input-note">Up to 1 MiB per snapshot. Supports text, CSV, Markdown, JSON, PDF, and plain-text Google Docs. Sheets become CSV with computed values. Import again to capture a newer version.</p><button className="button primary" disabled={disabled||!connected||!agent||!resource.trim()}>{busy?'Working…':'Import selected input'}</button>{!connected&&<p className="google-input-note">Connect and verify the account, then bind it to this project before importing.</p>}</form>
 {result&&<div className="google-import-result" role="status"><strong>Imported {result.receipt.resourceName}</strong><p>{result.versionIds.length} saved input · source version {result.receipt.resourceVersion} · {new Date(result.receipt.retrievedAt).toLocaleString()}</p>{result.receipt.range&&<p>{result.receipt.range} · {result.receipt.rowCount} rows</p>}{result.receipt.warnings.map(w=><p key={w}>{w}</p>)}<small>Source receipt saved with this snapshot. Assign it to a task from Files when needed.</small></div>}
 <footer><button className="text-button" disabled={disabled} onClick={()=>void run(onRefresh)}>Refresh status</button>{state?.connectedAccount&&<button className="text-button" disabled={disabled} onClick={()=>void run(onDisconnect)}>Disconnect Google Drive</button>}</footer></section>;
}
