import {useEffect,useRef,useState} from 'react';
import type {AppBridge,ExactCapabilityGrant} from '../../../packages/contracts';
export function ExactGrants({bridge,taskId}:{bridge:AppBridge;taskId:string}) {
 const [grants,setGrants]=useState<ExactCapabilityGrant[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const sequence=useRef(0),currentTask=useRef(taskId);currentTask.current=taskId;
 const refresh=()=>{const ticket=++sequence.current;if(!bridge.grants){setError('Grant inspection is unavailable.');return;}void bridge.grants({type:'grants.list',taskId}).then(next=>{if(ticket===sequence.current){setGrants(next);setError('');}},()=>{if(ticket===sequence.current)setError('Could not inspect exact grants.');});};
 useEffect(()=>{setGrants(null);setBusy(false);setError('');refresh();const off=bridge.onChanged(refresh);return()=>{sequence.current++;off();};},[bridge,taskId]);
 async function revoke(requestId:string){if(!bridge.grants)return;sequence.current++;setBusy(true);setError('');try{await bridge.grants({type:'grants.revoke',requestId});if(currentTask.current===taskId){setBusy(false);refresh();}}catch(e){if(currentTask.current===taskId)setError(e instanceof Error?e.message:'Future use could not be ended.');}finally{if(currentTask.current===taskId)setBusy(false);}}
 return <section aria-label="Exact capability grants"><h3>Exact grants</h3><p>Ending a grant fences future use. Completed uploads and publications remain. Pause this task before ending a grant.</p>{error&&<p role="alert">{error}<button className="button small" onClick={refresh}>Retry inspection</button></p>}{!grants&&!error&&<p role="status">Loading current grants…</p>}{grants&&(!grants.length?<p>No exact grants recorded.</p>:grants.map(g=><article key={g.requestId}><strong>{g.capability.name} · {g.currentAuthority?'Current authority':'Historical grant'}</strong><p>{g.authorityReason}</p><p>{g.capability.origin||'Project publication'} · {g.capability.versionIds.join(', ')}</p><small>Task {g.taskId} · granted {new Date(g.grantedAt).toLocaleString()}</small>{g.currentAuthority&&<button className="button small" disabled={busy} onClick={()=>void revoke(g.requestId)}>End future use</button>}</article>))}</section>;
}
