import { useEffect, useRef, useState } from 'react';
import type { ModelProviderApi, ModelProviderInput, ModelProviderProfile, ModelProviderKind, ModelProviderState, ModelProviderView } from '../../../packages/contracts/model-providers';
import './provider-settings.css';
const presets: { name: string; kind: ModelProviderKind; baseUrl: string; local?: boolean; noKey?: boolean }[] = [
  { name: 'OpenAI', kind: 'openai', baseUrl: 'https://api.openai.com/v1' },
  { name: 'Claude / Anthropic', kind: 'anthropic', baseUrl: 'https://api.anthropic.com/v1' },
  { name: 'Ollama on this Mac', kind: 'ollama', baseUrl: 'http://localhost:11434', local: true, noKey: true },
  { name: 'OpenRouter', kind: 'openai-compatible', baseUrl: 'https://openrouter.ai/api/v1' },
  { name: 'Together AI', kind: 'openai-compatible', baseUrl: 'https://api.together.xyz/v1' },
  { name: 'Groq', kind: 'openai-compatible', baseUrl: 'https://api.groq.com/openai/v1' },
  { name: 'LM Studio on this Mac', kind: 'openai-compatible', baseUrl: 'http://localhost:1234/v1', local: true, noKey: true },
  { name: 'LiteLLM gateway', kind: 'openai-compatible', baseUrl: 'http://localhost:4000/v1' },
  { name: 'Other compatible server', kind: 'openai-compatible', baseUrl: 'https://' },
];
function defaults(index: number): ModelProviderInput {
  const p = presets[index]; return { label: p.name, kind: p.kind, baseUrl: p.baseUrl, model: index === 0 ? 'gpt-4.1-mini-2025-04-14' : '', authentication: p.noKey ? 'none' : 'api-key', billing: p.local ? 'local' : 'metered', inputUsdPerMillion: index === 0 ? 0.4 : 0, outputUsdPerMillion: index === 0 ? 1.6 : 0, maxInputTokens: 32768, maxOutputTokens: 4096, toolCalling: true };
}
function inputFrom(p: ModelProviderView): ModelProviderInput { const { label, kind, baseUrl, model, authentication, billing, inputUsdPerMillion, outputUsdPerMillion, maxInputTokens, maxOutputTokens, toolCalling } = p; return { label, kind, baseUrl, model, authentication, billing, inputUsdPerMillion, outputUsdPerMillion, maxInputTokens, maxOutputTokens, toolCalling }; }
export function ProviderSettings({ api, active = false, onChanged }: { api: ModelProviderApi; active?: boolean; onChanged?(): void }) {
  const [state, setState] = useState<ModelProviderState>({ profiles: [], busy: false }), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const [open, setOpen] = useState(false), [preset, setPreset] = useState(0), [draft, setDraft] = useState<ModelProviderInput>(defaults(0)), [editing, setEditing] = useState<ModelProviderView | null>(null), [key, setKey] = useState(''), [repair, setRepair] = useState<ModelProviderProfile | null>(null), [toolsConfirmed, setToolsConfirmed] = useState(false);
  const generation = useRef(0), loaded = useRef(false);
  const [loadError, setLoadError] = useState('');
  async function refresh() { const ticket = ++generation.current; setLoading(true); setLoadError(''); try { const next = await api.command({ type: 'providers.state' }); if (ticket === generation.current) { setState(next); loaded.current = true; } } catch (e) { if (ticket === generation.current) setLoadError(e instanceof Error ? e.message : 'Connections could not be loaded.'); } finally { if (ticket === generation.current) setLoading(false); } }
  useEffect(() => { void refresh(); return () => { generation.current++; }; }, [api]);
  function reset() { setRepair(null); setOpen(false); setEditing(null); setKey(''); setToolsConfirmed(false); }
  async function command(action: Parameters<ModelProviderApi['command']>[0]) { const ticket = ++generation.current; setLoading(false); setBusy(true); setMessage(''); try { const next = await api.command(action); if (ticket === generation.current) { setState(next); loaded.current = true; setLoadError(''); } onChanged?.(); return true; } catch (e) { setMessage(e instanceof Error ? e.message : 'This connection change could not be saved.'); return false; } finally { setBusy(false); } }
  async function save() { const secret = key.trim(); setKey(''); if (await command({ type: 'providers.save', profile: draft, ...(editing ? { id: editing.id, expectedRevision: editing.revision } : {}), ...(secret ? { key: secret } : {}) })) { reset(); setMessage('Connection saved. No model request was sent. Select this model when creating a task.'); } }
  function repairKey(profile: ModelProviderProfile) { setRepair(profile); setOpen(false); setKey(''); setMessage(''); }
  async function saveExistingKey() { if (!repair) return; const secret = key.trim(); setKey(''); if (await command({ type: 'providers.saveKey', selectionId: repair.selectionId, key: secret })) { setRepair(null); setMessage('Key saved for that exact model revision. Its endpoint, model and limits are unchanged.'); } }
  const update = <K extends keyof ModelProviderInput>(field: K, value: ModelProviderInput[K]) => setDraft(d => ({ ...d, [field]: value }));
  return <section className="settings-section provider-settings"><div className="provider-heading"><div><h2>Models and providers</h2><p>Choose a model for each task. Connect cloud providers, a shared model gateway, or a model server you already run locally.</p></div><button className="button" disabled={busy || active} onClick={() => { setRepair(null); setEditing(null); setDraft(defaults(0)); setPreset(0); setKey(''); setToolsConfirmed(false); setOpen(true); }}>Add connection</button></div>
    <p className="provider-note">OpenAI and Claude are cloud services. Ollama and compatible servers can run local open models without an API key. This app does not download models or install a model server.</p>
    {loadError && <p role="alert">{loadError} <button className="button small" disabled={busy} onClick={() => void refresh()}>Retry loading connections</button></p>}
    {loading ? <p>Loading saved connections…</p> : !loaded.current ? null : state.profiles.length === 0 ? <p className="provider-empty">No additional connections yet. Your existing OpenAI connection remains available.</p> : <div className="provider-list">{state.profiles.map(p => <article className="provider-card" key={p.selectionId}><div><strong>{p.label}</strong><span className="provider-badge">{p.archived ? 'Archived' : p.billing === 'local' ? 'Local server' : 'Cloud / gateway'}</span><p>{p.model}</p><small>{p.baseUrl} · revision {p.revision}</small><p>{p.configured ? 'Configuration saved · connection not tested' : p.message || 'API key required'}</p><small>{p.billing === 'local' ? 'No provider fees recorded. Local compute is not measured.' : `Declared prices: $${p.inputUsdPerMillion} input / $${p.outputUsdPerMillion} output per million tokens.`}</small></div><div className="provider-card-actions"><button className="button" disabled={busy || active} onClick={() => { setRepair(null); setDraft(inputFrom(p)); setEditing(p); setKey(''); setToolsConfirmed(true); setOpen(true); }}>Edit</button>{!p.archived && <button className="button" disabled={busy || active} onClick={() => void command({ type: 'providers.archive', id: p.id, expectedRevision: p.revision })}>Archive</button>}{p.authentication === 'api-key' && <button className="button" disabled={busy || active} onClick={() => repairKey(p)}>Set key for this revision</button>}{p.authentication === 'api-key' && p.configured && <button className="button" disabled={busy || active} onClick={() => void command({ type: 'providers.removeKey', selectionId: p.selectionId })}>Remove key for this revision</button>}</div></article>)}</div>}
    {Boolean(state.history?.length) && <details className="provider-history"><summary>Previous connections retained by existing tasks</summary><p className="provider-note">These model settings stay fixed for saved tasks. Repair a key for its exact endpoint when access expires; archived connections are unavailable for new tasks.</p>{state.history?.map(p=><article className="provider-card" key={p.selectionId}><div><strong>{p.label} · revision {p.revision}</strong><p>{p.model}</p><small>{p.baseUrl}</small></div>{p.authentication==='api-key'&&<div className="provider-card-actions"><button className="button" disabled={busy||active} onClick={()=>repairKey(p)}>Set key for this revision</button><button className="button" disabled={busy||active} onClick={()=>void command({type:'providers.removeKey',selectionId:p.selectionId})}>Remove key for this revision</button></div>}</article>)}</details>}
    {repair && <form className="provider-form modal-form" onSubmit={e=>{e.preventDefault();void saveExistingKey();}}><h3>Repair connection key</h3><p>{repair.label} · revision {repair.revision} · {repair.model}</p><p className="provider-note">The key will be used only for {repair.baseUrl}. Saved tasks keep their original model and limits.</p><label>API key<input type="password" value={key} maxLength={1024} required autoComplete="off" spellCheck={false} disabled={busy} onChange={e=>setKey(e.target.value)}/></label><div className="provider-actions"><button className="button primary" disabled={busy||active||!key.trim()}>Save key for this revision</button><button className="button" type="button" disabled={busy} onClick={reset}>Cancel</button></div></form>}
    {open && <form className="provider-form modal-form" onSubmit={e => { e.preventDefault(); void save(); }}>
      <h3>{editing ? `Edit ${editing.label}` : 'Add a model connection'}</h3>
      {!editing && <label>Provider or server<select value={preset} disabled={busy} onChange={e => { const index = Number(e.target.value); setPreset(index); setDraft(defaults(index)); setKey(''); setToolsConfirmed(false); }}>{presets.map((p, i) => <option value={i} key={p.name}>{p.name}</option>)}</select></label>}
      <div className="provider-grid"><label>Connection name<input value={draft.label} maxLength={80} required disabled={busy} onChange={e => update('label', e.target.value)} /></label><label>Exact model ID<input value={draft.model} maxLength={192} required disabled={busy} placeholder={draft.kind === 'ollama' ? 'Installed model, including its tag' : 'Copy the model ID from your provider'} onChange={e => update('model', e.target.value)} /></label></div>
      <label>API base URL<input value={draft.baseUrl} type="url" required maxLength={512} disabled={busy || draft.kind === 'openai' || draft.kind === 'anthropic'} onChange={e => { update('baseUrl', e.target.value); setKey(''); }} /></label>
      <div className="provider-grid"><label>Authentication<select value={draft.authentication} disabled={busy || draft.kind === 'openai' || draft.kind === 'anthropic'} onChange={e => { update('authentication', e.target.value as ModelProviderInput['authentication']); setKey(''); }}><option value="api-key">API key in macOS Keychain</option><option value="none">No key — local or independently secured server</option></select></label><label>Billing<select value={draft.billing} disabled={busy || draft.kind === 'openai' || draft.kind === 'anthropic'} onChange={e => setDraft(d => ({ ...d, billing: e.target.value as ModelProviderInput['billing'], inputUsdPerMillion: 0, outputUsdPerMillion: 0 }))}><option value="metered">Provider or gateway charges</option><option value="local">No provider fees — localhost only</option></select></label></div>
      {draft.authentication === 'api-key' && <label>{editing ? 'Replacement API key (optional for the same endpoint)' : 'API key (can be added later)'}<input type="password" value={key} maxLength={1024} autoComplete="off" spellCheck={false} disabled={busy} onChange={e => setKey(e.target.value)} /><small>The key is cleared from this form after submission and stored only in macOS Keychain. A changed endpoint requires its own key.</small></label>}
      {draft.billing === 'metered' && <div className="provider-grid"><label>Input price — USD per million tokens<input type="number" min="0.000001" max="10000" step="0.000001" required value={draft.inputUsdPerMillion} onChange={e => update('inputUsdPerMillion', Number(e.target.value))} /></label><label>Output price — USD per million tokens<input type="number" min="0.000001" max="10000" step="0.000001" required value={draft.outputUsdPerMillion} onChange={e => update('outputUsdPerMillion', Number(e.target.value))} /></label></div>}
      <div className="provider-grid"><label>Reserved input tokens per call<input type="number" min="1024" max="200000" step="1" value={draft.maxInputTokens} onChange={e => update('maxInputTokens', Number(e.target.value))} /></label><label>Maximum output tokens per call<input type="number" min="64" max="4096" step="1" value={draft.maxOutputTokens} onChange={e => update('maxOutputTokens', Number(e.target.value))} /></label></div>
      <p className="provider-note">Each call reserves the full input allowance and maximum output at your declared prices. Reported usage settles the estimate; provider invoices, gateway fees and local compute may differ. Keep the combined token limits within the model’s context window.</p>
      <label className="provider-checkbox"><input type="checkbox" checked={toolsConfirmed} onChange={e => setToolsConfirmed(e.target.checked)} required />I selected a model that supports structured tool calls. Responses are checked before any tool runs.</label>
      <p className="provider-note">Text and one structured tool call per turn are supported. Models requiring reasoning-state replay or proprietary tool formats need a separate integration. Saved settings have not been tested with your provider.</p>
      {editing && <p>Saving creates a new revision. Existing tasks keep their previous model, endpoint and prices.</p>}
      <div className="provider-actions"><button className="button primary" disabled={busy || active || !toolsConfirmed}>Save connection</button><button className="button" type="button" disabled={busy} onClick={reset}>Cancel</button></div>
    </form>}
    {active && <p>Pause running tasks before changing model connections.</p>}{message && <p role="status">{message}</p>}
  </section>;
}
