import {useEffect, useRef, useState} from 'react';
import type {TaskRecoveryCommand, TaskRecoveryState} from '../../../packages/contracts/task-recovery';
import './routines.css';
export function RecoveryCenter({recovery, onChanged, onTask}: {recovery(command: TaskRecoveryCommand): Promise<TaskRecoveryState>; onChanged(listener: () => void): () => void; onTask(id: string): void}) {
  const [state,setState] = useState<TaskRecoveryState | null>(null), [error,setError] = useState(''), [busy,setBusy] = useState(false);
  const sequence = useRef(0);
  useEffect(() => {let alive = true; const refresh = () => {const ticket=++sequence.current; void recovery({type:'taskRecovery.state'}).then(v => {if(alive && ticket===sequence.current)setState(v);}, () => {if(alive)setError('Could not load automatic recovery.');});}; refresh(); const stop=onChanged(refresh); return () => {alive=false;stop();};}, [recovery,onChanged]);
  async function acknowledge(id: string) {setBusy(true); setError('');try {setState(await recovery({type:'taskRecovery.acknowledge',id}));}catch {setError('Could not acknowledge this recovery item.');}finally {setBusy(false);}}
  return <div className="page-scroll routines-page"><section className="page-heading"><div><span className="eyebrow">SAVED PROGRESS, BOUNDED REPAIR</span><h1>Automatic recovery</h1><p>See what the app repaired and what needs your attention.</p></div></section>
    <p className="routines-explainer">A temporary browser observation failure gets up to {state?.maxRetriesPerIncident ?? 2} delayed retries, with at most {state?.maxRetriesPerTask ?? 4} automatic retries across the task. Pausing stops retries. Login and MFA still need you; paid model calls and website changes are never replayed here.</p>
    {error && <p role="alert">{error}</p>}<section className="routine-card"><h2>{state?.needsAttention || 0} items need attention</h2>{!state?.incidents.length && <p>No browser recovery was needed yet.</p>}{state?.incidents.map(item => <article className="setting-row" key={item.id}><div><strong>{item.state==='recovered'?'Recovered automatically':item.state==='exhausted'?'Needs review':item.state==='interrupted'?'Interrupted':item.state==='cancelled'?'Stopped':'Recovering'}</strong><p>{item.message}</p><p>{new Date(item.updatedAt).toLocaleString()} · {item.attempts} retries reserved</p></div><div className="routine-actions"><button className="button" onClick={()=>onTask(item.taskId)}>Open task</button>{!item.acknowledged && ['exhausted','interrupted'].includes(item.state) && <button className="button" disabled={busy} onClick={()=>void acknowledge(item.id)}>Mark reviewed</button>}</div></article>)}</section></div>;
}
