import {useEffect,useRef,useState} from 'react';
import type {AppBridge,Agent} from '../../../packages/contracts';
import type {ProjectSpace} from '../../../packages/contracts/projects';
import type {RepositorySnapshotPreview} from '../../../packages/contracts/repository-snapshot';
export function RepositorySnapshotPilot({bridge,project,onCaptured}:{bridge:AppBridge;project:ProjectSpace;onCaptured():void}){
 const [agents,setAgents]=useState<Agent[]|null>(null),[agentId,setAgentId]=useState(''),[preview,setPreview]=useState<RepositorySnapshotPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const sequence=useRef(0),lock=useRef(false);
 function readAgents(){const ticket=++sequence.current;setAgents(null);setError('');void bridge.command({type:'snapshot'}).then(snapshot=>{if(ticket===sequence.current){const current=snapshot.agents.filter(a=>!a.archived&&project.agentIds.includes(a.id));setAgents(current);setAgentId(current[0]?.id||'');}},()=>{if(ticket===sequence.current)setError('Could not read current project agents. Retry inspection.');});}
 useEffect(()=>{setAgentId('');setPreview(null);setNotice('');readAgents();return()=>{sequence.current++;};},[bridge,project.id,project.agentIds.join(',')]);
 async function review(){if(lock.current||!agentId)return;lock.current=true;const ticket=++sequence.current;setBusy(true);setError('');setNotice('');setPreview(null);try{const result=await bridge.files({type:'repository.preview',projectId:project.id,agentId});if(ticket===sequence.current){if(result.repositoryPreview)setPreview(result.repositoryPreview);else if(result.cancelled)setNotice('Folder selection cancelled.');else setError('No snapshot preview was returned.');}}catch(e){if(ticket===sequence.current)setError(e instanceof Error?e.message:'Could not review the repository folder.');}finally{lock.current=false;setBusy(false);}}
 async function capture(){if(lock.current||!preview)return;lock.current=true;const ticket=++sequence.current;setBusy(true);setError('');try{const result=await bridge.files({type:'repository.capture',previewId:preview.previewId,identity:preview.identity,projectId:preview.projectId,agentId:preview.agentId});if(ticket===sequence.current){if(!result.versionIds?.length)throw Error('The captured version could not be identified.');setNotice('Exact snapshot saved in this project’s shared library. Select its published version as fleet evidence; nothing has started.');setPreview(null);onCaptured();}}catch(e){if(ticket===sequence.current)setError(e instanceof Error?e.message:'Could not save the reviewed snapshot.');}finally{lock.current=false;setBusy(false);}}
 return <details className="repository-pilot"><summary>Capture a repository source pilot</summary><p>Choose a local folder, then review the exact captured paths and exclusions. This pilot copies up to 16 text files and 32 KiB of source into one immutable JSON version up to 64 KiB. It does not establish full repository coverage or execute code.</p>{error&&<p role="alert">{error}{!agents&&<button type="button" className="button small" disabled={busy} onClick={readAgents}>Retry project agent inspection</button>}</p>}{notice&&<p role="status">{notice}</p>}{!agents?<p role="status">Loading current project agents…</p>:!agents.length?<p>Create an active agent in this project through Projects before capturing a snapshot.</p>:<><label>Snapshot owner<select disabled={busy} value={agentId} onChange={e=>{setAgentId(e.target.value);setPreview(null);sequence.current++;}}>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button type="button" className="button small" disabled={busy||!agentId} onClick={()=>void review()}>{busy?'Working…':'Choose folder and review snapshot'}</button></>}{preview&&<section aria-label="Reviewed repository snapshot"><p>Exact identity <code>{preview.identity}</code> · {preview.bytes} captured bytes · Commit {preview.snapshot.commit||'unknown'}.</p><p>{preview.snapshot.coverage}</p><h4>Captured files</h4><ul>{preview.snapshot.entries.map(entry=><li key={entry.path}><code>{entry.path}</code> · {entry.bytes} bytes · {entry.tracked===null?'Git status unknown':entry.tracked?'Tracked':'Untracked'} · {entry.dirty===null?'Dirty status unknown':entry.dirty?'Differs from commit':'Matches commit'} · <code>{entry.sha256}</code></li>)}</ul><h4>Exclusions and limits</h4>{preview.snapshot.exclusions.length?<ul>{preview.snapshot.exclusions.map((entry,n)=><li key={n}><code>{entry.path}</code> · {entry.reason}</li>)}</ul>:<p>No exclusions recorded within this bounded scan.</p>}<details><summary>Read captured content before saving</summary><pre style={{whiteSpace:'pre-wrap',maxHeight:320,overflow:'auto'}}>{JSON.stringify(preview.snapshot.entries,null,2)}</pre></details><p>Saving shares this exact version with agents in {project.name}. Model access occurs only when you select it and start a fleet. Secret detection is heuristic; review captured content before saving.</p><button type="button" className="button" disabled={busy} onClick={()=>void capture()}>Capture reviewed snapshot</button></section>}</details>;
}
