import {useEffect,useState,useRef} from 'react';
import type {AppBridge} from '../../../packages/contracts';
import type {RoutineCommand,RoutineState} from '../../../packages/contracts/routines';
import './routines.css';
export function Routines({bridge,onTask}:{bridge:AppBridge;onTask(id:string):void}){
 const [state,setState]=useState<RoutineState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[source,setSource]=useState(''),[title,setTitle]=useState(''),[time,setTime]=useState('09:00'),[timezone,setTimezone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone),[weekly,setWeekly]=useState(false),[day,setDay]=useState(1),[cap,setCap]=useState('5'),[cost,setCost]=useState('0.25'),[alertsEnabled,setAlertsEnabled]=useState(true);
 const alive=useRef(true),sequence=useRef(0),submitting=useRef(false),intent=useRef<Extract<RoutineCommand,{type:'routines.create'}>|null>(null);
 useEffect(()=>{intent.current=null;},[source,title,time,timezone,weekly,day,cap,cost,alertsEnabled]);
 const refresh=async()=>{const ticket=++sequence.current;try{const next=await bridge.routines({type:'routines.state'});if(alive.current&&ticket===sequence.current)setState(next);}catch(e){if(alive.current&&ticket===sequence.current)setError(e instanceof Error?e.message:'Could not load routines.');}};
 useEffect(()=>{alive.current=true;void refresh();const stop=bridge.onChanged(()=>void refresh());return()=>{alive.current=false;stop();};},[bridge]);
 async function act(command:RoutineCommand){const ticket=++sequence.current;setBusy(true);setError('');try{const next=await bridge.routines(command);if(alive.current&&ticket===sequence.current)setState(next);return true;}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Could not update the routine.');return false;}finally{if(alive.current)setBusy(false);}}
 async function create(){if(submitting.current)return;submitting.current=true;setBusy(true);setError('');try{if(!intent.current){const live=await bridge.live({type:'live.state'});const sourceRun=live.tasks.find(t=>t.taskId===source);if(!sourceRun)throw new Error('Choose an accepted source task.');const [hour,minute]=time.split(':').map(Number);intent.current={type:'routines.create',sourceTaskId:source,title,limits:{...sourceRun.limits,maxCostUsd:Number(cost)},monthlyCapUsd:Number(cap),expiresAt:Date.now()+90*86400000,timing:{timezone,hour,minute,weekdays:weekly?[day]:[0,1,2,3,4,5,6]},idempotencyKey:crypto.randomUUID(),alertsEnabled};}if(await act(intent.current)){intent.current=null;setTitle('');setSource('');}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Could not prepare the routine.');}finally{submitting.current=false;if(alive.current)setBusy(false);}}
 return <div className="page-scroll routines-page"><section className="page-heading"><div><span className="eyebrow">WORK THAT COMES BACK</span><h1>Routines</h1><p>Repeat a read-only job whose result you have accepted.</p></div><span className="local-chip">Runs on this Mac</span></section><p className="routines-explainer">Routines reuse the saved workflow, account, sources and exact input versions. Imported files are not refreshed automatically; change alerts compare saved reports and do not prove that a source changed. The app must be open and this Mac awake. Missed runs over 15 minutes are skipped; jobs never overlap. Sleep, backup and setup failures pause schedules for your review.</p>{error&&<p role="alert">{error}</p>}
 <section className="routine-card"><h2>Schedule an accepted job</h2>{!state?.eligible.length?<p>Run a read-only workflow and accept its output in Results to make it available here.</p>:<form className="routine-form" onSubmit={e=>{e.preventDefault();void create();}}>
 <label>Accepted job<select disabled={busy} required value={source} onChange={e=>setSource(e.target.value)}><option value="">Choose a result</option>{state.eligible.map(r=><option key={r.taskId} value={r.taskId}>{r.title.slice(0,100)}</option>)}</select></label><label>Routine name<input disabled={busy} required value={title} maxLength={100} onChange={e=>setTitle(e.target.value)}/></label><div className="routine-fields"><label>Frequency<select value={weekly?'weekly':'daily'} onChange={e=>setWeekly(e.target.value==='weekly')}><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label>{weekly&&<label>Day<select value={day} onChange={e=>setDay(Number(e.target.value))}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((v,i)=><option key={i} value={i}>{v}</option>)}</select></label>}<label>Time<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label></div><label>Timezone<input required value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><div className="routine-fields"><label>Maximum per run (USD)<input type="number" min="0.01" max="100" step="0.01" required value={cost} onChange={e=>setCost(e.target.value)}/></label><label>Maximum per calendar month (USD)<input type="number" min="0.01" max="1000" step="0.01" required value={cap} onChange={e=>setCap(e.target.value)}/></label></div><p className="routine-authorization">Enabling authorizes model runs within these limits for 90 days. Failed attempts count toward estimated spend. Every result still needs your review. Other limits cannot exceed the accepted run.</p><label className="routine-alert-choice"><input type="checkbox" checked={alertsEnabled} disabled={busy} onChange={e=>setAlertsEnabled(e.target.checked)}/>Show an in-app alert when a result differs from the earlier accepted result</label><button className="button primary" disabled={busy||!source}>Enable schedule</button></form>}</section>
 <section className="routine-card routine-alerts"><h2>Result changes <span className="local-chip">{state?.unreadAlerts||0} new</span></h2><p>New output is compared with the latest earlier accepted result, or the accepted job used to create the routine. Accepting an output in Results makes it eligible as the next baseline. Matching repeated changes are grouped into one alert. These are content comparisons, not factual verification.</p>{!state?.alerts.length&&<p>No changed-result alerts yet. Enable alerts on a routine to compare future completed outputs.</p>}{state?.alerts.map(alert=><article key={alert.id} className={'routine-change '+(alert.seen?'':'unread')}><div className="setting-row"><div><strong>{state.routines.find(r=>r.id===alert.routineId)?.title||'Routine'} · Result changed</strong><p>{new Date(alert.createdAt).toLocaleString()} · {alert.change.added} added / {alert.change.removed} removed {alert.change.unit}{alert.change.format==='csv'?' (including changed column declarations)':''}</p></div><div className="routine-actions"><button className="button" onClick={()=>onTask(alert.baselineTaskId)}>Earlier accepted result</button><button className="button" onClick={()=>onTask(alert.taskId)}>Changed result</button>{!alert.seen&&<button className="button" disabled={busy} onClick={()=>void act({type:'routines.acknowledgeAlert',id:alert.id})}>Mark reviewed</button>}</div></div><details><summary>Compare content</summary><div className="routine-diff"><div><h3>Removed from baseline</h3>{alert.change.removedExamples.map((line,i)=><pre key={i}>{line}</pre>)}{!alert.change.removedExamples.length&&<p>Nothing removed.</p>}</div><div><h3>Added to this result</h3>{alert.change.addedExamples.map((line,i)=><pre key={i}>{line}</pre>)}{!alert.change.addedExamples.length&&<p>Nothing added.</p>}</div></div><p>Up to eight short examples on each side. Open the exact saved outputs to inspect the complete difference. CSV row and column order, text spacing and paragraph wrapping are ignored.</p></details></article>)}</section>
 <section className="routine-card"><div className="setting-row"><h2>Saved routines</h2><button className="button" disabled={busy||!state?.routines.some(r=>r.enabled)} onClick={()=>void act({type:'routines.pauseAll'})}>Pause all schedules</button></div>{state?.routines.map(r=><article key={r.id} className="setting-row"><div><strong>{r.title}</strong><p>{r.enabled?'Next: '+new Date(r.nextRun).toLocaleString(undefined,{timeZone:r.timing.timezone})+' · '+r.timing.timezone:'Paused'} · ${r.limits.maxCostUsd}/run · ${r.monthlyCapUsd}/month</p>{r.lastError&&<p>{r.lastError}</p>}</div><div className="routine-actions"><button className="button" disabled={busy} onClick={()=>void act({type:'routines.setAlerts',id:r.id,enabled:!r.alertsEnabled})}>{r.alertsEnabled?'Alerts on':'Alerts off'}</button><button className="button" disabled={busy} onClick={()=>void act({type:'routines.setEnabled',id:r.id,enabled:!r.enabled})}>{r.enabled?'Pause':'Enable'}</button></div></article>)}</section>
 <section className="routine-card"><h2>Run history</h2>{!state?.occurrences.length&&<p>No scheduled occurrences yet.</p>}{state?.occurrences.map(o=><article className="setting-row" key={o.id}><div><strong>{state.routines.find(r=>r.id===o.routineId)?.title} · {o.state}</strong><p>{new Date(o.dueAt).toLocaleString()} · estimated ${o.costUsd.toFixed(4)}</p>{o.reason&&<p>{o.reason}</p>}{o.comparison&&<p><strong>{o.comparison.state==='changed'?'Result changed':o.comparison.state==='unchanged'?'No content change':'Comparison unavailable'}</strong> · {o.comparison.message}</p>}</div>{o.taskId&&<button className="button" onClick={()=>onTask(o.taskId!)}>Open run</button>}</article>)}</section></div>;
}
