import {useEffect,useRef,useState} from 'react';
import type {AppBridge,Snapshot,Task,Agent} from '../../../packages/contracts';
import {useFilePreview} from './Files';
import type {TaskHistoryState} from '../../../packages/contracts/history';
export function TaskHistory({bridge,snapshot,onTask}:{bridge:AppBridge;snapshot:Snapshot;onTask(task:Task):void}){
 const [agentPage,setAgentPage]=useState<{agents:Agent[];cursor:string|null}>({agents:[],cursor:null}),[scope,setScope]=useState<'active'|'archived'>('active'),[agentId,setAgentId]=useState(''),[state,setState]=useState<TaskHistoryState|null>(null),[detail,setDetail]=useState<TaskHistoryState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const sequence=useRef(0),preview=useFilePreview();
 useEffect(()=>{const ticket=++sequence.current;setState(null);setDetail(null);setError('');if(!bridge.taskHistory){setError('History inspection is unavailable.');return;}void Promise.all([bridge.taskHistory({type:'tasks.history',scope,agentId:agentId||null,cursor:null}),bridge.taskHistory({type:'agents.history',scope,cursor:null})]).then(([next,agents])=>{if(ticket===sequence.current){setState(next);setAgentPage({agents:agents.agents||[],cursor:agents.nextAgentCursor||null});}},()=>{if(ticket===sequence.current)setError('Could not read history.');});return()=>{sequence.current++;};},[bridge,scope,agentId]);
 async function inspect(taskId:string,cursor:string|null=null){if(!bridge.taskHistory||busy)return;const ticket=sequence.current;setBusy(true);setError('');try{const next=await bridge.taskHistory({type:'tasks.inspect',taskId,cursor});if(ticket===sequence.current)setDetail(previous=>cursor?{...next,messages:[...(previous?.messages||[]),...(next.messages||[])]}:next);}catch(e){if(ticket===sequence.current)setError(e instanceof Error?e.message:'Exact history unavailable.');}finally{if(ticket===sequence.current)setBusy(false);}}
 async function page(){if(!bridge.taskHistory||!state?.nextCursor||busy)return;const ticket=sequence.current;setBusy(true);try{const next=await bridge.taskHistory({type:'tasks.history',scope,agentId:agentId||null,cursor:state.nextCursor});if(ticket===sequence.current)setState(previous=>previous?{...next,tasks:[...previous.tasks,...next.tasks.filter(t=>!previous.tasks.some(p=>p.id===t.id))]}:next);}catch(e){setError(e instanceof Error?e.message:'Older tasks unavailable.');}finally{setBusy(false);}}
 async function archive(taskId:string){if(!bridge.taskHistory||busy)return;setBusy(true);setError('');try{await bridge.taskHistory({type:'tasks.archive',taskId,archived:scope==='active'});const next=await bridge.taskHistory({type:'tasks.history',scope,agentId:agentId||null,cursor:null});setState(next);setDetail(null);}catch(e){setError(e instanceof Error?e.message:'Archive change unavailable.');}finally{setBusy(false);}}
 async function archiveAgent(id:string,archived:boolean){if(!bridge.taskHistory||busy)return;setBusy(true);setError('');try{await bridge.taskHistory({type:'agents.archive',agentId:id,archived});const next=await bridge.taskHistory({type:'tasks.history',scope,agentId:agentId||null,cursor:null});setState(next);const agents=await bridge.taskHistory({type:'agents.history',scope,cursor:null});setAgentPage({agents:agents.agents||[],cursor:agents.nextAgentCursor||null});}catch(e){setError(e instanceof Error?e.message:'Agent archive change unavailable.');}finally{setBusy(false);}}
async function olderAgents(){if(!bridge.taskHistory||busy||!agentPage.cursor)return;setBusy(true);setError('');try{const next=await bridge.taskHistory({type:'agents.history',scope,cursor:agentPage.cursor});setAgentPage(previous=>({agents:[...previous.agents,...(next.agents||[])],cursor:next.nextAgentCursor||null}));}catch(e){setError(e instanceof Error?e.message:'Older agent history unavailable.');}finally{setBusy(false);}}
 return <div className="page-scroll"><h1>History and archive</h1><p>Archive retains files, exact references and accounting. Finished tasks with resolved effects release active history capacity. Archive all of an agent’s tasks before archiving that agent. Restore returns browsing capacity and never starts work. Retained bytes still count toward storage.</p><details><summary>Agent history capacity</summary>{agentPage.agents.map(a=><article className="setting-row" key={a.id}><span>{a.name} · {a.archived?'Archived':'Active'}</span><button className="button" disabled={busy} onClick={()=>void archiveAgent(a.id,!a.archived)}>{a.archived?'Restore agent to browse':'Archive agent'}</button></article>)}{agentPage.cursor&&<button className="button" disabled={busy} onClick={()=>void olderAgents()}>Load next agents</button>}</details><label>View<select value={scope} disabled={busy} onChange={e=>setScope(e.target.value as typeof scope)}><option value="active">Unarchived history</option><option value="archived">Archived tasks</option></select></label><label>Agent<select value={agentId} disabled={busy} onChange={e=>setAgentId(e.target.value)}><option value="">All agents</option>{[...new Map([...snapshot.agents,...agentPage.agents].map(a=>[a.id,a])).values()].map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{error&&<p role="alert">{error}</p>}{!state&&!error&&<p role="status">Loading bounded history…</p>}{state?.tasks.map(t=><article className="setting-row" key={t.id}><div><strong>{t.objective}</strong><p>{t.state} · exact task {t.id}</p></div><div><button className="button" disabled={busy} onClick={()=>void inspect(t.id)}>Inspect exact history</button>{!t.archived&&<button className="button" onClick={()=>onTask(t)}>Open task</button>}{['succeeded','failed','cancelled'].includes(t.state)&&<button className="button" disabled={busy} onClick={()=>void archive(t.id)}>{scope==='active'?'Archive':'Restore to browse'}</button>}</div></article>)}{state&&!state.tasks.length&&<p>No tasks in this scoped page.</p>}{state?.nextCursor&&<button className="button" disabled={busy} onClick={()=>void page()}>Load next tasks</button>}{detail&&<section><h2>Exact saved task history</h2><code>{detail.tasks[0]?.id}</code>{detail.messages?.map(m=><article key={m.id}><strong>{m.role}</strong><p style={{whiteSpace:'pre-wrap'}}>{m.content}</p></article>)}{detail.messageNextCursor&&<button className="button" disabled={busy} onClick={()=>void inspect(detail.tasks[0].id,detail.messageNextCursor!)}>Read next messages</button>}{detail.versionIds?.map(id=><button className="button" key={id} onClick={()=>preview(id)}>Inspect exact file {id}</button>)}<details><summary>Exact references and held accounting</summary><pre>{JSON.stringify({versionIds:detail.versionIds,requests:detail.requests,accounting:detail.accounting},null,2)}</pre></details></section>}</div>;
}
