import type {LiveCommand,LiveLimits,LivePolicy} from './live';
export class LiveError extends Error {constructor(readonly code:string,message:string){super(message);this.name='LiveError';}}
export const liveFail=(code:string,message:string):never=>{throw new LiveError(code,message);};
export function record(v:unknown,keys:string[]):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||![Object.prototype,null].includes(Object.getPrototypeOf(v))||Object.keys(v).some(k=>!keys.includes(k)))return liveFail('invalid_command','This live command is not supported.');return v as Record<string,unknown>;}
export function string(v:unknown,max=4096):string{if(typeof v!=='string'||!v.trim()||Buffer.byteLength(v)>max||v.includes('\0'))return liveFail('invalid_command','A required value is missing or too long.');return v.trim();}
export function identity(v:unknown):string{const s=string(v,96);if(!/^[A-Za-z0-9_-]+$/.test(s))return liveFail('invalid_command','Select an existing item.');return s;}
export function number(v:unknown,min:number,max:number,integer=true):number{if(typeof v!=='number'||!Number.isFinite(v)||(integer&&!Number.isSafeInteger(v))||v<min||v>max)return liveFail('invalid_command','A configured limit is outside its supported range.');return v;}
export function parseLimits(raw:unknown):LiveLimits{const v=record(raw,['maxCostUsd','maxModelCalls','maxToolSteps','maxActiveSeconds','maxTokens']);return{maxCostUsd:number(v.maxCostUsd,0.01,10,false),maxModelCalls:number(v.maxModelCalls,1,100),maxToolSteps:number(v.maxToolSteps,1,200),maxActiveSeconds:number(v.maxActiveSeconds,10,3600),maxTokens:number(v.maxTokens,1000,1_000_000)};}
export function parsePolicy(raw:unknown):LivePolicy{const v=record(raw,['mode','allowedOrigins','mailAccount','browserInteraction','mailDetail']);if(!['workspace','read_only_browser'].includes(String(v.mode))||!Array.isArray(v.allowedOrigins)||v.allowedOrigins.length>12)liveFail('invalid_command','Choose a supported policy and at most twelve allowed website origins.');const origins=(v.allowedOrigins as unknown[]).map(x=>{const s=string(x,256);let u:URL;try{u=new URL(s);}catch{return liveFail('invalid_command','Use a complete HTTPS website origin.');}if(u.protocol!=='https:'||u.origin!==s||u.username||u.password||u.port||!u.hostname.includes('.'))liveFail('invalid_command','Use a complete HTTPS website origin without a path or credentials.');return s;});if(new Set(origins).size!==origins.length)liveFail('invalid_command','Website origins must be unique.');const mailAccount=v.mailAccount===undefined?undefined:string(v.mailAccount,254);if(mailAccount&&(!/^[A-Za-z0-9._%+-]+@gmail\.com$/.test(mailAccount)||v.mode!=='read_only_browser'||!origins.includes('https://mail.google.com')))liveFail('invalid_command','The mail account requires a read-only Gmail policy.');if(v.browserInteraction!==undefined&&(v.browserInteraction!=='reviewed_actions'||v.mode!=='workspace'||mailAccount))liveFail('invalid_command','Reviewed browser actions require a workspace task without a Gmail account.');if(v.mailDetail!==undefined&&(v.mailDetail!=='threads_and_attachments'||!mailAccount))liveFail('invalid_command','Detailed mail access requires an exact read-only Gmail account.');return{mode:v.mode as LivePolicy['mode'],allowedOrigins:origins,...(mailAccount?{mailAccount}: {}),...(v.browserInteraction?{browserInteraction:'reviewed_actions' as const}:{}),...(v.mailDetail?{mailDetail:'threads_and_attachments' as const}:{})};}
export function parseLiveCommand(raw:unknown):LiveCommand{
 const type=record(raw,['type','agentId','objective','completionCriteria','model','policy','limits','taskId','requestId','revision']).type;
 if(type==='live.state'){record(raw,['type']);return{type};}
 if(type==='live.resources'){const v=record(raw,['type','taskId']);return{type,taskId:identity(v.taskId)};}
 if(type==='live.repairRequest'){const v=record(raw,['type','taskId','requestId','revision']);if(!Number.isSafeInteger(v.revision)||Number(v.revision)<1)liveFail('invalid_command','Choose the current request revision.');return{type,taskId:identity(v.taskId),requestId:identity(v.requestId),revision:Number(v.revision)};}
 if(type==='live.start'||type==='live.pause'||type==='live.stop'){const v=record(raw,['type','taskId']);return{type,taskId:identity(v.taskId)};}
 if(type==='live.createTask'){const v=record(raw,['type','agentId','objective','completionCriteria','model','policy','limits']);return{type,agentId:identity(v.agentId),objective:string(v.objective,8000),completionCriteria:string(v.completionCriteria,4000),model:string(v.model,100),policy:parsePolicy(v.policy),limits:parseLimits(v.limits)};}
 return liveFail('invalid_command','This live command is not supported.');
}
